### ISSUE TITLE
Add IPv6 support for flickr

### ISSUE THREAD

**Issue by zmz125000** [lennylxx/ipv6-hosts#102]
> ## Flickr
> 2001:4998:14:800::1001 flickr.com
> 2001:4998:14:800::1001 www.flickr.com
> 2001:4998:14:800::1001 up.flickr.com
> 2001:4998:14:800::1001 api.flickr.com
> 68.142.240.50 secure.flickr.com
> 2001:4998:14:800::1001 m.flickr.com
> 124.108.101.31 heartbeat.flickr.com
> 192.0.79.33 code.flickr.com
> 2001:4998:14:800::4005 c.staticflickr.com
> 2001:4998:14:800::4005 c1.staticflickr.com
> 2001:4998:14:800::4005 c2.staticflickr.com
> 2001:4998:14:800::4005 c3.staticflickr.com
> 2001:4998:14:800::4005 c4.staticflickr.com
> 2001:4998:14:800::4005 c5.staticflickr.com
> 2001:4998:14:800::4005 c6.staticflickr.com
> 2001:4998:14:800::4005 c7.staticflickr.com
> 2001:4998:14:800::4005 c8.staticflickr.com
> #2406:2000:fc:402::c:2207 c9.staticflickr.com
> 124.108.101.57 s.yimg.com #s.gycs.b.yahoodns.net

**Comment by lennylxx** [comment]
Thanks for the suggestion. I tried several times, using IPv4 can normally access flickr in education network.
So there is no need to use IPv6 I think?
IPv6 seems not fully supported by flickr so I don't put this section in other files. And since `12_ipv4.txt` is updated with the parameter of A type address, changing to IPv6 manually is doable, but next time it still will be set to IPv4.

**Comment by AlexanderMisel** [comment]
我这边搜到的是
```
## Flickr
69.147.76.173 flickr.com
2406:2000:a0:800::1001 www.flickr.com
2406:2000:a0:800::1001 up.flickr.com
2406:2000:a0:800::1001 api.flickr.com
68.142.240.50 secure.flickr.com
2406:2000:a0:800::1001 m.flickr.com
124.108.101.31 heartbeat.flickr.com
192.0.79.33 code.flickr.com
2406:2000:fc:402::c:2207 c.staticflickr.com
2406:2000:fc:402::c:2207 c1.staticflickr.com
2406:2000:fc:402::c:2207 c2.staticflickr.com
2406:2000:fc:402::c:2207 c3.staticflickr.com
2406:2000:fc:402::c:2207 c4.staticflickr.com
2406:2000:fc:402::c:2207 c5.staticflickr.com
2406:2000:fc:402::c:2207 c6.staticflickr.com
2406:2000:fc:402::c:2207 c7.staticflickr.com
2406:2000:fc:402::c:2207 c8.staticflickr.com
#2406:2000:fc:402::c:2207 c9.staticflickr.com
2406:2000:ec:a01::2002 s.yimg.com #s.gycs.b.yahoodns.net
```

**Comment by zmz125000** [comment]
I agree that it is no need to use IPv6 since IPv6 support for farm*.staticflickr.com is unavailable.
