### ISSUE TITLE
不能访问YouTube的视频

### ISSUE THREAD

**Issue by abearxiong** [lennylxx/ipv6-hosts#107]
可以进网站，但是视频访问不了。一直转。为啥，噗！

**Comment by Chengcheng-Xiao** [comment]
昨天突然出现的情况，看了一下log是在connecting redirector.gvt1.com:443里connection refuse了。

**Comment by rongwwei** [comment]
这个要怎么弄？

**Comment by lennylxx** [comment]
试试换成这个IP `2401:3800:4001:11::100e`，这个IP属于北京谷翔机房。
突然发现上次大规模更新 (0b1ab0c8d887b0a945e03a745a2beae25625ca14) 之后，host中出现了不少北京的服务器，应该是最近Google有什么动作，在北京部署了大量新的机器。

更新之前 (246ff7bf64a6ae5dea5e92abfe4e4fd101d5a6ab)：
```
~/ipv6-hosts$ grep 2401:3800 hosts | wc -l
13
```
更新之后 (0b1ab0c8d887b0a945e03a745a2beae25625ca14)：
```
~/ipv6-hosts$ grep 2401:3800 hosts | wc -l
1133
```
现在 (fcf52c78b59f443ffbc007751e2028c58aef12a1)：
```
~/ipv6-hosts$ grep 2401:3800 hosts | wc -l
1325
```

**Comment by Chengcheng-Xiao** [comment]
谢谢 lennylxx ，将所有2404:6800:4005:80a::200e改成2401:3800:4001:11::100e后恢复正常。

**Comment by shuangzhijinghua** [comment]
2401:3800早几年前就有了吧..
http://bgp.he.net/AS24424#_prefixes6

**Comment by lennylxx** [comment]
@shuangzhijinghua  嗯，但是之前只有 2401:3800:4001:1::/48 - 2401:3800:4001:7::/48，最近新添加了2401:3800:4001:9::/48 - 2401:3800:4001:11::/48 还有2401:3800:4001:806::/48、2401:3800:4001:807::/48等等。

**Comment by abearxiong** [comment]
谢谢，可以了    试了Chengcheng-Xiao 的方法就可以了。
