### ISSUE TITLE
Please update ---sn-cnoa-pmje.googlevideo.com related hosts, thanks!

### ISSUE THREAD

**Issue by Exisser** [lennylxx/ipv6-hosts#114]
Please update ---sn-cnoa-pmje.googlevideo.com related hosts, thanks!

**Comment by ppoozl** [comment]
I updated yesterday. Please wait the owner to merge

**Comment by lennylxx** [comment]
Thanks to @ppoozl, they are added in https://github.com/lennylxx/ipv6-hosts/pull/115

**Comment by Exisser** [comment]
Thanks a lot!!!
