### ISSUE TITLE
又上不去了，地址又变了？

### ISSUE THREAD

**Issue by rongwwei** [lennylxx/ipv6-hosts#119]

**Comment by phy25** [comment]
什么上不去，我这边正常？

**Comment by lennylxx** [comment]
如果你希望你的问题得到解决，请起码描述清楚你遇到的问题以及你已经尝试过的措施。
像“又上不去了，地址又变了”这种没有明显意义的标题，以及空白的描述是没办法让别人帮助你的。
开issue前请先阅读https://github.com/lennylxx/ipv6-hosts/issues/13

**Comment by ppoozl** [comment]
西北地区？西安？教育网？西安教育网光纤被挖断了

**Comment by rongwwei** [comment]
好吧，我ping了下，ipv6的地址，ping不通，我还以为是我新装系统的问题，所以来看看是不是都出问题了，原来是光纤又被挖了。。。

**Comment by qieaaa** [comment]
2333交大那边挖地铁给挖断了，现在好像好了
