### ISSUE TITLE
谷歌和脸书上不去 （北京联通 6to4）

### ISSUE THREAD

**Issue by yanhujk** [lennylxx/ipv6-hosts#121]
ipv6 ping不通 ，不知道是什么问题，但是维基却可以上

**Comment by phy25** [comment]
`tracert www.google.com` 试试？

**Comment by yanhujk** [comment]
6   249 ms   249 ms   248 ms  google-router1.peering.surf.net [2001:610:f16:6080::82]
 7   249 ms   249 ms   249 ms  2001:4860:0:f8d::2
 8   249 ms   253 ms   249 ms  2001:4860::c:4000:d9a9
 9   326 ms   326 ms   327 ms  2001:4860::c:4000:cf5b
10     *        *        *     请求超时。

**Comment by wendykohn** [comment]
谷歌北京联通 6to4 
[My Repair Release.docx](https://github.com/lennylxx/ipv6-hosts/files/1026723/My.Repair.Release.docx)

**Comment by yanhujk** [comment]
今天能上去了
