### ISSUE TITLE
Twitter 分支的 hosts 不可用

### ISSUE THREAD

**Issue by dawnlau** [lennylxx/ipv6-hosts#128]
Twitter 的 hosts 失效很久了其实。。。可能 ip 封干净了吧。。。

**Comment by qieaaa** [comment]
@dawnlau twitter的一直都不能用，，

**Comment by dawnlau** [comment]
@qieaaa 年初还好的，之后不能用了以后又用了一段时间老D的，然后64的那几天用不了了，找了其他的也用不了，应该是封干净了。。。

**Comment by LGA1150** [comment]
暂时无解。
