### ISSUE TITLE
How to utilize Issues system better

### ISSUE THREAD

**Issue by lennylxx** [lennylxx/ipv6-hosts#13]
1. Issues system is not a forum
2. Read  [LICENSE](https://github.com/lennylxx/ipv6-hosts/blob/master/LICENSE) and [README#privacy](https://github.com/lennylxx/ipv6-hosts#Privacy)
3. When you come across a problem, try these steps first
   - Read wiki https://github.com/lennylxx/ipv6-hosts/wiki
   - Google Search
4. Before you ask
   - Read [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)
   - Chinese version [提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)
5. When you ask
   - Be nice
   - **English** is preferred
   - Attach useful information, describe what you have tried
   - Use Markdown
6. Pull Requests are welcome :)
7. Do not send issues to my email, mail is used for private contact.

**Comment by LiveChief** [comment]
this is literally common sense but your right sometimes people don't even have that.
