### ISSUE TITLE
可否提供下'domain = address'的格式呢？

### ISSUE THREAD

**Issue by mgdreamingstar** [lennylxx/ipv6-hosts#135]
如下的格式：
`'www.mozilla.org = 2400:cb00:2048:1::6810:2902'`
因手机更改 hosts 需要这样的格式，但每次修改很繁琐。

**Comment by lennylxx** [comment]
抱歉，暂时没有该计划。
如果你需要的话，可以自己写Python脚本生成，逻辑非常简单。也欢迎发起脚本的Pull Request。:)
