### ISSUE TITLE
Are Google Facebook YouTube Wikipedia etc. all down? seriously

### ISSUE THREAD

**Issue by BruceZac** [lennylxx/ipv6-hosts#136]
Are you guys encountered with the same problem? Now... please tell me

**Comment by zeapoem** [comment]
Shaanxi xian，all down

发自我的超级手机

2017年7月27日 09:14于 Bruce Xiangcai Zhang <notifications@github.com>写道：

Are you guys encountered with the same problem? Now... please tell me

―

**Comment by BruceZac** [comment]
Oh no… Haidian district, Beijing. Please tell me this is just a temporary technical problem…

**Comment by zxyqwe** [comment]
Same in BJ, all down

**Comment by BBBob** [comment]
Same in Haidian, but it's all right!

**Comment by BruceZac** [comment]
alright guys, everything's fine now, in Haidian, Beijing at least..that really scared the shit out of me
