### ISSUE TITLE
GFW启用针对ip的拦截？

### ISSUE THREAD

**Issue by zyc199847** [lennylxx/ipv6-hosts#137]
坐标武大，以前偶尔连接不上v6地址，最近改hosts，使用纯v6各种折腾都提示连接超时，但是室友的电脑却能正常通过v6访问google和油管。难道gfw已启用针对ip的黑名单？

**Comment by ppoozl** [comment]
能提够一下开发者控制台截图

**Comment by zyc199847** [comment]
![1](https://user-images.githubusercontent.com/14220017/28820710-380e9b92-76e5-11e7-9166-49d43b15ea93.png)
![2](https://user-images.githubusercontent.com/14220017/28820712-39a5dc86-76e5-11e7-9d95-887f381a68ae.png)
都不用开控制台了。。以前遇到这种情况拔网线然后清一下dns缓存就行，现在也不行。

**Comment by ppoozl** [comment]
tracert 呢

**Comment by zyc199847** [comment]
![3](https://user-images.githubusercontent.com/14220017/28820891-e7c53cbc-76e5-11e7-834a-767e21294713.png)
目测在武大到CERNET的地方被拦住了

**Comment by ppoozl** [comment]
你都没出你们学校呢

**Comment by ppoozl** [comment]
我估计你的所以IPV6流量都没出去

**Comment by zyc199847** [comment]
我觉得也是，但是室友就没问题，很奇怪

**Comment by ppoozl** [comment]
这不是GFW的锅，问你们学校的网管吧

**Comment by zyc199847** [comment]
好吧。。issue终结
