### ISSUE TITLE
优化Facebook速度

### ISSUE THREAD

**Issue by LGA1150** [lennylxx/ipv6-hosts#14]
2a03:2880:f002::/48是 Facebook香港CDN
而在你的hosts中用的是洛杉矶（2a03:2880:f00d::/48）和圣何塞（2a03:2880:f022::/48）的IP
建议更换为香港的以提速
例子：
2a03:2880:f002:1:face:b00c:0:1 star.c10r.facebook.com
2a03:2880:f002:b:face:b00c:0:3 scontent-a.xx.fbcdn.net

其他如 2a03:2880:10（或20、2130等）::/48 不用更换

**Comment by lennylxx** [comment]
我在 [如何加速](https://github.com/lennylxx/ipv6-hosts/wiki/How-to-speed-up) 这里研究过这个问题，得出的结论是使用香港 CDN 速度并不会快，使用洛杉矶速度应该是最快的。

并且我 (北京教育网) 刚才 traceroute 了一下，`2a03:2880:f002:1:face:b00c:0:1` 这个 IP 是不可达的。

附上结果：
```
traceroute to 2a03:2880:f002:1:face:b00c:0:1 (2a03:2880:f002:1:face:b00c:0:1), 30 hops max, 80 byte packets
 1  fc00:101:101::1 (fc00:101:101::1)  0.551 ms  0.508 ms  0.410 ms
 2  * * *
 3  * * *
 4  cernet2.net (2001:da8:ae:ae:812::1)  13.998 ms * *
 5  cernet2.net (2001:da8:ae:1000::2)  14.236 ms  14.970 ms  15.351 ms
 6  * * *
 7  bupt-buaa-v6.cernet2.net (2001:da8:1:1d::1)  11.917 ms * *
 8  * * *
 9  * * *
10  2001:252:0:100::2 (2001:252:0:100::2)  131.946 ms  131.975 ms  132.157 ms
11  * * *
12  10gigabitethernet13-10.core1.lax2.he.net (2001:470:0:2a2::1)  281.521 ms  281.370 ms  281.442 ms
13  10ge3-2.core1.tyo1.he.net (2001:470:0:294::2)  384.866 ms  384.894 ms  384.887 ms
14  10ge5-2.core1.hkg1.he.net (2001:470:0:26a::2)  437.059 ms  426.658 ms  426.562 ms
15  facebook1-lacp-10G.hkix.net (2001:7fa:0:1::ca28:a16e)  428.982 ms !H  426.003 ms !H  425.825 ms !H
```
```
PING 2a03:2880:f002:1:face:b00c:0:1(2a03:2880:f002:1:face:b00c:0:1) 56 data bytes
From 2001:7fa:0:1::ca28:a16e icmp_seq=1 Destination unreachable: Address unreachable
From 2001:7fa:0:1::ca28:a16e icmp_seq=2 Destination unreachable: Address unreachable
From 2001:7fa:0:1::ca28:a16e icmp_seq=3 Destination unreachable: Address unreachable
From 2001:7fa:0:1::ca28:a16e icmp_seq=4 Destination unreachable: Address unreachable
^C
--- 2a03:2880:f002:1:face:b00c:0:1 ping statistics ---
4 packets transmitted, 0 received, +4 errors, 100% packet loss, time 3002ms
```

**Comment by LGA1150** [comment]
现已改到HKIX，可以用了
以下是正解：
2a03:2880:f002:109:face:b00c:0:2 star.c10r.facebook.com
2a03:2880:f002:110:face:b00c:0:3 scontent-a.xx.fbcdn.net

**Comment by shuangzhijinghua** [comment]
@LGA1150 回线不走HKIX，还是过HE LAX，看延迟就看出来了。所以还是没啥加速效果

**Comment by LGA1150** [comment]
@shuangzhijinghua 
```
 9    18 ms    36 ms    20 ms  wh-gz-v6.cernet2.net [2001:da8:1:2::1]
 10    36 ms    36 ms    36 ms  bj-wh-v6.cernet2.net [2001:da8:1:1::1]
 11     *        *        *     请求超时。
 12     *        *        *     请求超时。
 13    77 ms    77 ms    77 ms  facebook1-lacp-10G.hkix.net [2001:7fa:0:1::ca28:a16e]
 14    78 ms    78 ms    78 ms  psw01d.hkg3.tfbnw.net [2620:0:1cff:dead:beef:ffff:ffff:fe6b]
 15    78 ms    78 ms    78 ms  po4.msw1aa.01.hkg3.tfbnw.net [2a03:2880:f002:ffff::9d]
 16    77 ms    77 ms    77 ms  facebook.com [2a03:2880:f002:109:face:b00c:0:2]
```

**Comment by shuangzhijinghua** [comment]
不过现在原作者不维护了，自己维护一个吧
2015年10月22日 下午11:20，"LGA1150" <notifications@github.com>写道：

**Comment by lennylxx** [comment]
@LGA1150  我看到你也创建了一个相关的项目，不知是否是因为之前我中断更新的缘故。
我最近被一些私人事情所困，可能更新不够频繁。如果方便的话，我想邀请你成为本项目的 collaborator。一者可以保证本项目的正常更新，二者也可以避免开源项目分支过多，参与者贡献力量分散的问题。

**Comment by LGA1150** [comment]
@lennylxx 
No problem.

**Comment by LGA1150** [comment]
@lennylxx 
你可以看到我的项目中，有很多域名是查不到AAAA记录的，但我还是找到了它们的官方IPv6地址，想了解一下吗？

**Comment by lennylxx** [comment]
@LGA1150 我注意到了。
比如这个地址，`2001:778:0:ffff:64::68f4:2a01`，在这里 http://bgp.he.net/ip/2001:778:0:ffff:64::68f4:2a01 查到的所有者并不是 Twitter。

Twitter 的所有 IP 段在这里 http://bgp.he.net/AS13414

**Comment by shuangzhijinghua** [comment]
那是立陶宛的NAT64地址段，dns64.litnet.lt可以将没有AAAA记录的域名IP转换为IPV6地址
2015年10月30日 上午12:06，"lennylxx" <notifications@github.com>写道：

**Comment by LGA1150** [comment]
@lennylxx @shuangzhijinghua 
这个我知道，但你们有没有注意到 `2400:cb00:2048:1::` `2600:1417:9::` `2406:da00:ff00::` 为前缀的地址？

**Comment by shuangzhijinghua** [comment]
这个就没见过了，全球ping推特域名都没有见v6地址，可以猜测是某人做的一个代理吧。sniproxy就可以做。
2015年10月30日 上午12:13，"LGA1150" <notifications@github.com>写道：

**Comment by LGA1150** [comment]
@shuangzhijinghua 
提示： `2400:cb00:2048:1::` 为 Cloudflare 地址段， `2600:1417:9::` 为 Akamai 香港地址段， `2406:da00:ff00::` 为 Amazon ELB 美国地址段。

**Comment by shuangzhijinghua** [comment]
这个就真没见过了，具体地址看看？
2015年10月30日 上午12:20，"LGA1150" <notifications@github.com>写道：

**Comment by LGA1150** [comment]
@shuangzhijinghua 
那我分别举一个栗子：
`2400:cb00:2048:1::6810:1904 www.digitalocean.com`
`2600:1417:9:192::e59 download.microsoft.com`
`2406:da00:ff00::6b15:d598 status.github.com`

**Comment by lennylxx** [comment]
@LGA1150  这些可能来自 CDN  或者 NAT64 的地址如果我们需要加入到 hosts 中，我建议还是新建一个 issue 或者 wiki 页面详细解释我们这样做的原因，以打消其他用户的疑虑。

另外我们在这里每次只发一句的进行版聊是不是不太合适？
建议在这里 https://gitter.im/lennylxx/ipv6-hosts 进行即时沟通。

**Comment by XIAOSpider97** [comment]
2400:cb00:2048 这是cloudflare CDN的IP段。

lennylxx <notifications@github.com>于2015年10月30日周五 00:32写道：
