### ISSUE TITLE
是否可以在路由器端使用？

### ISSUE THREAD

**Issue by lnedpaul** [lennylxx/ipv6-hosts#140]
本人梅林固件，之前用WinSCP改过ipv4的hosts，可以实现部分网站的科学上网，最近在折腾6in4 tunnel，请问在路由器上是否可以使用ipv6版hosts文件，如何设置？谢谢。

**Comment by lennylxx** [comment]
可以，路由器如果是基于Linux的，可以直接替换`/etc/hosts`，具体的步骤你需要参照你的路由器相应的配置方法。
