### ISSUE TITLE
请问github有没有ipv6的地址？

### ISSUE THREAD

**Issue by EFCHolla** [lennylxx/ipv6-hosts#144]
学校宿舍环境只有ipv6，请问github有ipv6的地址吗？

**Comment by zeapoem** [comment]
有，hosts文件你打开看一下

发自我的超级手机

2017年9月17日 19:05于 Xu Zhang <notifications@github.com>写道：

学校宿舍环境只有ipv6，请问github有ipv6的地址吗？

―

**Comment by LGA1150** [comment]
主站没有， *.github.io 倒是有（Fastly CDN）
你也可以使用第三方的转换服务，但不保证安全：
http://bbs2.6plat.org/d/21
https://gh6.eu/

**Comment by lychichem** [comment]
Github官方说他们已经“准备好了”IPV6地址，但“尚未”开始使用，所以现在主站是没有的

**Comment by xiaoyan94** [comment]
你可以通过代理让所有流量都走IPV6

**Comment by xiaoyan94** [comment]
我就是这么干的，所有ipv4网站都走IPV6代理，同样不花流量，现在ipv6站也就谷歌全系列支持而已
