### ISSUE TITLE
Pixiv惨遭封锁

### ISSUE THREAD

**Issue by lychichem** [lennylxx/ipv6-hosts#145]
如题，应该是今天早上9点左右开始的，先是移动网，再下来电信，现在校园网（电信出口）都受到影响了
根据微博方面的情报，应该是DNS泛域名投毒，IP本身没事，但是不知道什么风向

**Comment by sy618** [comment]
个人抓包搜集到的有关pixiv域名：
pixiv.net
www.pixiv.net
app-api.pixiv.net
accounts.pixiv.net
touch.pixiv.net
oauth.secure.pixiv.net
source.pixiv.net
imgaz.pixiv.net
d.pixiv.org
pixiv.pximg.net
i.pximg.net


ipv4：https://raw.githubusercontent.com/sy618/hosts/master/data/pixiv

**Comment by Leakless** [comment]
自己抓的一些子域名：

210.140.92.140	img-novel.pximg.net
210.140.92.140	public-img-comic.pximg.net
210.140.92.140	pixiv.pximg.net
210.140.92.140	i.pximg.net
#6个IP做dns负载均衡，210.140.92.134-210.140.92.141

210.140.131.157	d.pixiv.org
#4个IP做dns负载均衡，210.140.131.157-210.140.131.160

210.140.170.179	sketch.pixiv.net

210.140.131.144	source.pixiv.net
210.140.131.144	novel.pixiv.net
210.140.131.144	imgaz.pixiv.net
210.140.131.144	comic.pixiv.net
#4个IP做dns负载均衡，210.140.131.144-210.140.131.147

210.129.120.44	www.pixivision.net
210.129.120.44	www.pixiv.me
210.129.120.44	www.pixiv.net
210.129.120.44	www.pixiv.co.jp
210.129.120.44	touch.pixiv.net
210.129.120.44	sensei.pixiv.net
210.129.120.44	recruit.pixiv.net
210.129.120.44	pixivision.net
210.129.120.44	m.pixiv.net
210.129.120.44	factory.pixiv.net
210.129.120.44	embed.pixiv.net
210.129.120.44	dic.pixiv.net
210.129.120.44	chat.pixiv.net
210.129.120.44	accounts.pixiv.net
210.129.120.44	pixiv.net
210.129.120.44	app-api.pixiv.net
#3个IP做dns负载均衡，210.129.120.41，210.129.120.43，210.129.120.44

210.129.120.41	oauth.secure.pixiv.net
#2个IP做dns负载均衡，210.129.120.41，210.129.120.43

210.129.120.20	booth.pm
210.129.120.20	s.booth.pm
210.129.120.20	asset.booth.pm
#2个IP做dns负载均衡，210.129.120.19，210.129.120.20

**Comment by bushizhu** [comment]
哦，可以提交其他的hosts吧，这个只是ipv6的校园网使用

**Comment by zmz125000** [comment]
210.140.131.144 img-sketch.pixiv.net

**Comment by wanzzhehe** [comment]
还有一个。。
167.89.118.52	link.pixiv.net
