### ISSUE TITLE
I hope to add support for arxiv.org

### ISSUE THREAD

**Issue by Feywell** [lennylxx/ipv6-hosts#146]
Recently I usually visit arxiv.org. It is very useful for some people.
Thank you!

**Comment by lennylxx** [comment]
I checked that arxiv.org is not censored, it doesn't have IPv6 address neither.
Do you have trouble accessing it?

**Comment by Feywell** [comment]
@lennylxx  I just think it is so slow to visit. Is there some ways to accelerate？
Thank you！
