### ISSUE TITLE
微软系CDN可以加入项目

### ISSUE THREAD

**Issue by lychichem** [lennylxx/ipv6-hosts#149]
`2606:2800:147:120f:30c:1ba0:fc6:265a     ajax.aspnetcdn.com #cs9.wpc.v0cdn.net`，测试中发现这个IP好像还能用于`software-download.microsoft.com`

**Comment by LGA1150** [comment]
这个 IP 教育网会绕路，可以用 `2606:2800:11f:17a5:191a:18d5:537:22f9`
另外可能是由于安全原因， Windows 会忽略 hosts 中 `*.microsoft.com *.windowsupdate.com` 之类的条目
