### ISSUE TITLE
ipv6-hosts打不开Google等网站

### ISSUE THREAD

**Issue by ylwszb** [lennylxx/ipv6-hosts#152]
环境：电信网络，win7系统，已配置ipv6，并在 “http://test-ipv6.com/” 网站做测试，ipv6全部测试成功

安装：已经下载最新的hosts文件并放入系统hosts文件夹内，并已经执行过 “ipconfig /flushdns” 命令

问题：浏览器还是无法打开Google网站，是不是hosts又挂了，还是我哪里设置的不对。

**Comment by LGA1150** [comment]
是 IPv6 隧道？目前某墙已经有过滤隧道和 HTTPS SNI 的功能

**Comment by xiuluo** [comment]
教育网IPV6可以通过这个hosts打开Google

**Comment by tec1987** [comment]
我这也有这种情况，测试发现，部分IPv6地址无法连接，可能是被封了，找一些可用的IPv6地址就可以了
