### ISSUE TITLE
Twitter无法连接

### ISSUE THREAD

**Issue by Luxios** [lennylxx/ipv6-hosts#153]
我开启了ipv6后，无法连接Twitter，其他的youtube等都能使用
搜索后发现twitter不支持ipv6，看到此repo支持twitter，于是下载了https://raw.githubusercontent.com/lennylxx/ipv6-hosts/master/hosts
替换win10系统的host，依旧无效

**Comment by LGA1150** [comment]
Twitter IPv4 地址全部遭封杀，外加 HTTPS SNI 关键字屏蔽，目前无解。
