### ISSUE TITLE
能不能讲讲两个脚本怎么用

### ISSUE THREAD

**Issue by masktao** [lennylxx/ipv6-hosts#157]
作者你好:
用你的Host文件,跌跌撞撞弄进路由器实现了翻
但这两个脚本文件实在不知道怎么用,在哪用?可以直接指点下吗?
update_hosts.py
merge_snippets.sh

**Comment by lennylxx** [comment]
Read #13 and the wiki [Do it yourself](https://github.com/lennylxx/ipv6-hosts/wiki/Do-It-Yourself) before you open a new issue.

**Comment by kobepejanash** [comment]
朋友你好，请问你知道那两个更新文件怎么用了吗？求指点
