### ISSUE TITLE
请添加谷歌相册域名

### ISSUE THREAD

**Issue by shuangzhijinghua** [lennylxx/ipv6-hosts#16]
`ap[0-9]\.googleusercontent\.com`
另外查询到`ap1000000000.googleusercontent.com`也可返回记录，初步估计和`docs-{2}[a-z0-9]-{2}[a-z0-9]-doc.googleusercontent.com`一样。

**Comment by lennylxx** [comment]
sorry, 你从哪得到的这些地址，我找不到。
何不列出来？

**Comment by shuangzhijinghua** [comment]
ap1.googleusercontent.com
ap2.googleusercontent.com
ap3.googleusercontent.com
ap4.googleusercontent.com
ap5.googleusercontent.com
ap6.googleusercontent.com
ap7.googleusercontent.com
ap8.googleusercontent.com
ap9.googleusercontent.com

手机更新谷歌相册应用，原有的hosts加载不出图片，wireshark抓包就看到了请求的域名。话说电信的IPV6已经解墙，走教育网的出口，你的hosts可能有很大的作用了。

**Comment by lennylxx** [comment]
不过最近维基百科无法访问了。

**Comment by shuangzhijinghua** [comment]
IPV4用198地址段应该可以。V6没问题，电信手机能直连。
