### ISSUE TITLE
wifi怎么用ipv6-hosts

### ISSUE THREAD

**Issue by jasoncwj** [lennylxx/ipv6-hosts#162]
网络是教育网，支持ipv6
有线的时候使用ipv6-hosts可以用，但是用wifi就不行
怎么让wifi连接的网络也可以用ipv6的hosts呢

**Comment by LGA1150** [comment]
谁的 wifi?

**Comment by jasoncwj** [comment]
就是学校网络的wifi，应该也是教育网的
但是用wifi连的这个hosts就不起作用呢

**Comment by phy25** [comment]
请确认你的 WiFi 环境是否因为 AP、手机接入等原因不支持 IPv6，可以尝试访问 http://test-ipv6.com/ 或 http://testmyipv6.com/

**Comment by BruceZac** [comment]
我也想问这个问题，好像手机得root了才能修改hosts？
