### ISSUE TITLE
@lennylxx

### ISSUE THREAD

**Issue by RomanSmile** [lennylxx/ipv6-hosts#163]
请原谅在这里打开新的问题，只是不知道怎么联系，
这里一些东西你看看如果可以请添加到
snippets/1e100.txt里面
[1e100.net旧金山.txt](https://github.com/lennylxx/ipv6-hosts/files/1456799/1e100.net.txt)

**Comment by lennylxx** [comment]
Changes be done in 398e3cf5b59115151a78ab490a97c567ebf94b5e.

**Comment by RomanSmile** [comment]
@lennylxx 
感谢lennylxx
好一个授人以鱼不如授人以渔！

**Comment by lennylxx** [comment]
不用谢，应该感谢你为这个项目添加新数据。
