### ISSUE TITLE
不情之请

### ISSUE THREAD

**Issue by 5cylinders** [lennylxx/ipv6-hosts#166]
先谢谢主人的工作。
update_hosts.py需要python3环境，有没有可能提供一个mac自带的2.7环境下可用的脚本呢？（也许这要求有点过分了，而且MAC里也没带某些模块。）

**Comment by lennylxx** [comment]
d101fc3bd30021123e2a588c53275a6b5d16cfcc 更新之前是 Python 2.7，https://github.com/lennylxx/ipv6-hosts/blob/f211191069eec49c082e1bc0898d83624d623450/update_hosts.py

**Comment by 5cylinders** [comment]
@lennylxx 我在mac环境里针对01_google.txt运行了若干分钟，始终是Total: 1089 lines, Done: 0 lines, Ratio: 0 %.这样一个结果。换了个DNS也是如此。我的错误在哪里？

**Comment by lennylxx** [comment]
你的网络环境有IPv6连接吗？如果没有，需要指定为IPv4的DNS。

**Comment by 5cylinders** [comment]
有。test-ipv6.com通过。一直用您的ipv6 hosts ，最近google 搜索失效，才想自己更新一下01那部分IP。——失效的表现是部分google地址如G的主页，一闪即逝，然后再闪也不闪，完全连不上，而另一些，如gmail, play，连接正常。似乎遭到某种针对性的屏蔽。也许update脚本失灵也是因为这个原因。

**Comment by lennylxx** [comment]
建议你采取以下措施：
1. 到https://github.com/lennylxx/ipv6-hosts/blob/master/snippets/1e100.txt 里面挑一个IP换到www.google.com，然后再试试。
2. 打开developer tools，看看出错原因是什么
3. 不行就只能wireshark抓包分析了

**Comment by 5cylinders** [comment]
先是怎么弄也不行。重启了一下光纤猫，奇怪的事情发生了，您的hosts全能用了。不明觉历：），再次感谢帮助。
