### ISSUE TITLE
@lennylxx

### ISSUE THREAD

**Issue by RomanSmile** [lennylxx/ipv6-hosts#169]
我不是很清楚怎么正确的方式提交给你审查，发起的请求也不是正确，还是在这里提交给你吧好吗，
麻烦你手动提取，经过审查以正确的方式添加，另外反馈一下有关这个项目的事情，xx项目ipv6不是经过什么扫描，全部提取这个项目的sn----部分，导致这个hosts文件里面的ip越来越慢，很是担心这个项目会不会被他们拖垮，
[ams-1e100.txt](https://github.com/lennylxx/ipv6-hosts/files/1478211/ams-1e100.txt)

**Comment by lennylxx** [comment]
xx项目？你指什么？有链接吗

**Comment by RomanSmile** [comment]
这是他们提取的文件

这是连接自己去看，
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/good_ipv6.txt

**Comment by RomanSmile** [comment]
问题我已经反馈了这个issues就关闭了吧，

**Comment by lennylxx** [comment]
抄就抄吧，这只是我的业余爱好小项目，为了高校学生查阅资料方便弄的。
我自己并不使用这个hosts，工作环境也不需翻墙就可以访问Google。
如果最后真的因为滥用搞砸了，那后果由滥用者自负。

**Comment by BruceZac** [comment]
直觉维护吧大家，且用且珍惜

**Comment by 2378** [comment]
反正我是多手准备
GAE系目标太大
被玩烂也不是没可能

**Comment by xiuluo** [comment]
这都能抄啊，也是佩服
