### ISSUE TITLE
dl.google.com

### ISSUE THREAD

**Issue by leisiji** [lennylxx/ipv6-hosts#175]
由于需要在 android studio 下载 android sdk，但是发现不能上 dl.google.com。

**Comment by LGA1150** [comment]
3.0 似乎不支持 IPv6 
直接去掉这行或者再加一行 v4 的

**Comment by lychichem** [comment]
没记错的话这个应该是能直连北京服务器的……会不会是别的链接卡住了

**Comment by leisiji** [comment]
试了一下从官方下载一个 Android studio 的安装包，发现用这个 ipv6 的地址会出现 dns 解析错误，应该是这个地址有问题；后来把这一行删了，就可以了。
