### ISSUE TITLE
最近有更新的计划吗？

### ISSUE THREAD

**Issue by dalton-chiou** [lennylxx/ipv6-hosts#176]
我这里（联通宽带）至少一周连不上google了。开始是主站连不上，接着ipv6.google.com不行了，现在gmail也不行了。都能ping通，就是连不上。唉。

**Comment by LGA1150** [comment]
#152

**Comment by dalton-chiou** [comment]
6to4隧道。试过update_hosts_py，找出的IP仍然不行。

**Comment by LGA1150** [comment]
无解，你可以选择使用 ISATAP 隧道或者其他代理。
