### ISSUE TITLE
About new GGC gosun-xuz1 

### ISSUE THREAD

**Issue by lennylxx** [lennylxx/ipv6-hosts#178]
#177 提到新出现一组GGC 服务器，gosun-xuz1，sn编码为bvn0o-m01e。
目前只支持IPv4，whois信息显示属于CHINANET，位于中国江苏南京。
```
222.187.0.204 r1---sn-bvn0o-m01e.googlevideo.com
222.187.0.205 r2---sn-bvn0o-m01e.googlevideo.com
222.187.0.206 r3---sn-bvn0o-m01e.googlevideo.com
222.187.0.207 r4---sn-bvn0o-m01e.googlevideo.com
222.187.0.208 r5---sn-bvn0o-m01e.googlevideo.com
222.187.0.209 r6---sn-bvn0o-m01e.googlevideo.com
222.187.0.210 r7---sn-bvn0o-m01e.googlevideo.com
222.187.0.211 r8---sn-bvn0o-m01e.googlevideo.com
```

大概搜索了一下，gosun似乎代表了高升控股，中国电信与其子公司高升科技有合作关系。
猜测电信通过高升作为GGC合作方接入了Google的网络，但是还没启用IPv6？
难道大陆的ISP也开始支持GGC了？
如果没记错的话好像还是第一次出现。

http://www.gosun.com/service/idc_data.html
https://3g.163.com/tech/article/B8Q9GT98000915BD.html

**Comment by LGA1150** [comment]
xuz→江苏徐州

**Comment by lennylxx** [comment]
嗯，注册地为南京但机房可能位于徐州。

**Comment by ppoozl** [comment]
https://bgp.he.net/ip/222.187.0.204#_ipinfo
--------------------------------------------------
IP段是江苏的。

**Comment by ppoozl** [comment]
找到个新的机房
139.209.52.76 r1---sn-bvn0o-jb9e.googlevideo.com

**Comment by ppoozl** [comment]
可能还有更多，明天找找看

**Comment by LGA1150** [comment]
其实 C3EDGE 也有 GGC，我之前还收集了一些来着
https://gist.github.com/LGA1150/54205db851c8775c1287

**Comment by LGA1150** [comment]
```
117.175.92.76 r1.gosun-ctu1.gvt1.com
117.175.92.77 r2.gosun-ctu1.gvt1.com
117.175.92.78 r3.gosun-ctu1.gvt1.com
117.175.92.79 r4.gosun-ctu1.gvt1.com
117.175.92.80 r5.gosun-ctu1.gvt1.com
117.175.92.81 r6.gosun-ctu1.gvt1.com
117.175.92.82 r7.gosun-ctu1.gvt1.com
117.175.92.83 r8.gosun-ctu1.gvt1.com
```
成都移动

**Comment by ppoozl** [comment]
都没有v6 毕竟国内v6还没铺开，v6出口就一个BJIX
