### ISSUE TITLE
fbcdn的列表不全

### ISSUE THREAD

**Issue by lychichem** [lennylxx/ipv6-hosts#184]
目前已知仅有scontent.xx.fbcdn.net是不够的，这个系统可能包含n个形如scontent-sit4-1.xx.fbcdn.net这样的域名，估计其中4和1应该是可变数字，只是不知道有多少，分别用于页面不同资源，比如我发现的这个至少控制我自己的fb资料页的背景图

**Comment by lychichem** [comment]
I think this also caused #209 , let's put them together here. We need to consider whether we have to add a large list of fbcdn servers to this repository.

**Comment by lennylxx** [comment]
@lychichem We can definitely do that, as long as the pattern of fbcdn.net is clear. As for the hosts file size increasing, we can remove useless ones at the same time.

**Comment by lychichem** [comment]
@lennylxx Today I found some domains already in facebook.txt was given a wrong IP. I used google public DNS V6 and got IP different from the file.  And the wrong IP cause facebook fail to load some resources. Could you please update this file? I'm using Windows and therefor not easy to run scripts to update this file.
