### ISSUE TITLE
update_hosts.py 需要处理新型DNS污染

### ISSUE THREAD

**Issue by lennylxx** [lennylxx/ipv6-hosts#186]
刚才试着用`update_hosts.py`更新了一次，发现有不少用于DNS污染的错误的IP没有被过滤出来。
比如：

| IPv6查询结果 | 域名 | IP实际所有者 | 
| --- |---|---|
31.13.64.33 | www.google.com | Facebook
208.101.60.87 | encrypted.google.com | SoftLayer
69.171.230.18 | google.com.hk | Facebook
64.13.192.76 | accounts.google.com.hk | Media Temple
31.13.68.22 | clients1.google.com.hk | Facebook
69.63.180.173 | mobile.google.com.hk | Facebook
208.101.21.43 | clients1.google.com.tw | SoftLayer

这些IP和之前的黑洞IP性质并不相同，是真实可用的IP，某些你甚至可以Ping通。
以前固定的黑名单列表已经不够用了。
现在的DNS污染是固定黑洞IP列表/动态Fake IP/错误IP混淆 三种方式同时使用。
不得不说GFW这一招借力打力还是有点厉害的。

至于如何解决这个问题，用白名单来过滤查询结果应该是一种方法
https://github.com/lennylxx/ipv6-hosts/wiki/AS15169
https://bgp.he.net/AS15169#_prefixes6
https://github.com/myguybetter/GoogleIPHunter (这个目前还没有收录IPv6)

**Comment by lrinQVQ** [comment]
咩,还有一些地方直接返回空解析2333真404不存在的

**Comment by lrinQVQ** [comment]
以及关于wiki中的AS15169可能需要更正一下
根据ARIN(American Registry for Internet Numbers)中AS15169的记录
https://whois.arin.net/rest/net/NET6-2001-4860-1.html
Google持有2001:4860::/32整个地址池

**Comment by CNMan** [comment]
这个脚本还有个问题：如果input中有重复域名，会出现错误，生成不了output

**Comment by SodiumAzide** [comment]
昨天写了一个脚本，尝试抓取IP，获得了一批确实可以ping通的IP，但是换进host后，仍然不能连上Google。刚刚验证了一下，并没有出现你说的这种情况
