### ISSUE TITLE
是不是我的网络问题？？？

### ISSUE THREAD

**Issue by RomanSmile** [lennylxx/ipv6-hosts#187]
仔细手动检测08_googlevideo,为什么只剩下8000多可用服务器呢？
我是两条宽带，一条电信，一条联通，两条线路一样结果，
2a00:1450:401f
2a00:1450:4020
对应的sn服务器全部不通，可是2001:4860:4860::8888 与2001:470:0:9d::2解析出的ip与08_googlevideo文件一致，怀疑是不是我的网络有问题？看看你们检测结果怎么样？除了这些还有这些服务器也是废弃的，
` uv2pm-ugoe,a8au-5goe,ug5onuxaxjvh-jx3e,
ug5onuxaxjvh-304e,ug5onuxaxjvh-bvwe,30a7dn7y,30a7dne7,
30a7dnel,30a7dnes,30a7dn7e,30a7dn7l,30a7dn7s,30a7dn7z,
30a7en7s,30a7en76,30a7dne6,30a7dned,30a7en7z,30a7en7d,
30a7dner,qxa7en7e,qxa7en7l,qxa7en7s,qxa7en7z,q4f7snss,
q4f7snsk,q4f7snsr,q4f7snsy,q4f7snz7,q4f7snly,q4f7sns7,
q4f7snsz,a5m7znez,a5m7zne6,a5m7zned,a5m7znek,a5m7zne7,
a5m7lnes,a5m7lnez,a5m7lne6,a5m7lned,a5m7lnek,a5m7lner,
hp57knsk,hp57knsr,hp57knsy,hp57knz7,hp57knze,hp57kn76,
hp57kn7d,hp57kn7k,hp57kn7r,hp57kn7y,hp57kne7,hp57knee,
hp57knel,hp57knzl,hp57knzs,vgqsenl6,vgqsenld,vgqsense,
vgqsensl,nx5e6n7s,nx5e6n7z,tt17dnel,tt17dn7rtt17dn7y,
tt17dne7,tt17dnee,tt17rn76,tt17rn7d,tt17rn7k,tt17rn7r,
i3b7kn7y,i3b7kne7,i3b7knee,i3b7knel,i3b7knek,i3b7kner,
i3b7kney,i3b7knl7,qxo7sn7e,qxo7sn7l,qxo7sn7s,qxo7sn7k,
qxo7sn7r,qxo7snel,9gv7en7e,9gv7en7l,9gv7en7s,9gv7en7z,
9gv7en76,9gv7en7d,9gv7en7k,9gv7en7r,5uaezne6,5uaezned,
vgqs7n7e,vgqs7n7l,vgqs7n7s,vgqs7n7z,vgqs7n76,vgqs7n7d,
vgqs7n7k,vgqs7n7r,vgqs7n7y,vgqs7ne7,vgqs7nee,vgqs7nel,
vgqs7ne6,vgqs7ned,q4f7sn7y,q4f7sne7,q4f7snee,q4f7snel,
q4f7snes,q4f7snez,q4f7snez,q4f7sne6,q4f7sned,q4f7snek,
q4f7sner,q4f7sney,q4f7snl7,q4f7snle,q4f7snll,q4f7snls,
q4f7snlz,q4f7snl6,q4f7snld,q4f7snlk,q4f7snlr,q4f7snse,
q4f7snsl,q4f7sns6,q4f7snsd,a5m7ln7s,a5m7ln7d,a5m7ln7z,
a5m7ln76,a5m7ln7d,a5m7ln7k,a5m7ln7r,a5m7ln7y,a5m7lne7,
a5m7znee,a5m7lnee,a5m7znel,a5m7lnel,n4v7kn7e,n4v7kn7l,
n4v7kn7s,n4v7kn7z,n4v7kn7d,n4v7kn7k,n4v7kn7r,n4v7kne7,
n4v7knee,n4v7knel,o097zne7,o097znee,o097znel,o097znes,
o097znez,o097zne6,o097zned,o097znek,o097znl7,o097znle,
o097znll,o097znls,ab5l6n7e,ab5l6n7l,ab5l6n7s,ab5l6n7z,
ab5l6n76,ab5l6n7d,ab5l6n7k,ab5l6n7r,ab5l6n7y,ab5l6ne7,
ab5l6nee,ab5l6nel,ab5l6nes,ab5l6nez,ab5l6ne6,ab5l6ned,
ab5l6nek,ab5l6ner,ab5l6ney,x1x7sn7k,x1x7sn7r,x1x7sn7y,
x1x7sne7,x1x7snee,x1x7snel,x1x7snes,x1x7snez,4g57knky,
4g57knre,4g57knrl,4g57knrs,4g57knrz,hpa7zne7,hpa7znee,
hpa7znel,hpa7znes,hpa7znek,h5q7dnek,h5q7dnl7,h5q7dnle,
h5q7dnll,hgn7zn7e,hgn7zn7l,hgn7zn76,hgn7zn7d,hgn7zn7k,
hgn7zn7r,hgn7zn7s,hgn7zn7z,5hnednls,5hnednlz,5hnednl6,
5hnednld,5hne6nls,5hne6nlz,5hne6nl6,n8v7ln7r,n8v7ln7y,
n8v7lne7,n8v7lnee,n8v7lnel,n8v7lnes,n8v7lnez,n8v7lne6,
n8v7sn7e,n8v7sn7l,n8v7sn7s,n8v7sn7z,n8v7sn76,n8v7sn7d,
n8v7sn7k,n8v7znl7,n8v7zn7e,n8v7zn7l,n8v67n7e,n8v67n7l,
2gb7ln7e,2gb7ln7l,2gb7ln7s,2gb7ln7z,2gb7ln76,2gb7ln7d,
2gb7ln7k,2gb7ln7r,3c27ln7e,3c27ln7l,3c27ln7s,3c27ln76,
3c27sn7s,3c27ln7d,3c27ln7k,3c27ln7r,3c27ln7y,h0j7sn7s,
h0j7sn7z,h0j7sn76,h0j7sn7d,h0j7sn7y,h0j7sne7,h0j7snee,
h0j7snel,nv47ln7d,4wg7en7e,4wg7en7l,f5f7ln7e,f5f7ln7l,
f5f7ln7s,f5f7ln7z,5hne6n76,5hne6n7d,hne6n7k,5hne6n7r,
5hne6n7y,5hne6ne7,5hne6nee,5hne6nel,5hne6nes,5hne6nez,
5hne6ne6,5hne6ned,5hne6nek,5hne6ner,5hne6ney,5hne6nl7,
5hnedn76,5hnedn7d,5hnedn7k,5hnedn7r,5hnedn7y,5hnedne7,
5hnednee,5hnednel,5hnednes,5hnednez,5hnedne6,5hnedned,
5hnednek,5hnedner,5hnedney,5hnednl7,4g57kn7e,4g57kn7l,
4g57kn7s,4g57kn7z,4g57kn76,4g57kn7d,4g57knes,4g57knez,
4g57kne6,4g57kned,4g57knek,4g57kner,4g57kney,4g57knl7,
4g57knle,4g57knll,4g57knls,4g57knlz,4g57knl6,4g57knld,
4g57knsy,4g57knz7,4g57knze,4g57knzl,4g57knzs,4g57knzz,
4g57knz6,4g57knzd,4g57knzk,4g57knzr,4g57knzy,4g57kn67,
4g57kn6e,4g57kn6l,4g57kn6s,4g57kn6z,4g57kn66,4g57kn6d,
4g57kn6k,4g57kn6r,4g57kn6y,4g57knd7,4g57knde,4g57kndl,
4g57knd6,4g57kndd,4g57kndk,4g57kndr,4g57kndy,4g57knk7,
4g57knke,4g57knkl,4g57knks,4g57knkz,4g57knk6,4g57knkd,
aiglln7e,aigl6n7s,aigl6n7z,aigl6n76,aiglln7z,aigl6n7d,
aiglln76,aiglln7d,aiglln7k,aiglln7r,aiglln7y,aigllne7,
aigllnee,aigllnel,aigllnes,aigllnez,aigllne6,aigllned,
aigllnek,aigllner,aigllney,aigllnl7,aigllnle,aigllnll,
aigllnls,aigllnlz,aigllnl6,aigllnld,aigllnlk,aigllnlr,
aigllnly,aigllns7,aigllnse,aigllnsl,aigllnss,aigllnsz,
aigllns6,aigllnsd,aigllnsk,aigllnsr,aigllnsy,aigllnz7,
aigllnze,aigllnzl,`
如果我的网络没问题，为什么这么多不可用呢？开始怀疑我的网络了，

**Comment by ppoozl** [comment]
好像6IN4 GFW已经可以处理了

**Comment by ppoozl** [comment]
服务器的话应该是撤V6了，现在还是V4主导吧

**Comment by RomanSmile** [comment]
@ppoozl 
这些废弃的我们做更新应该怎么取舍呢？留着不能用，删除让文件变得更加整洁，另外很多我提出的不能用服务器，我自己感觉是做了更新调整，废弃的ri---20组的居多，出现新的组合r1---r5 r6居多，

**Comment by lennylxx** [comment]
@RomanSmile 比较好的方式是不管是废弃的还是可用的都维护在google docs里面，但是这个工作量太大，如果能写个程序自动搞就好了。

**Comment by RomanSmile** [comment]
为了达到精准度我自己手动检测每一个服务器，两宽带测试求证，已经清除了废弃的，添加新发现的服务器，2a00:1450:401f 2a00:1450:4020，他们对应的全部废弃，添加了这些，
`add vgqskned,vgqsrnll,vgqsknek,q4flrney,
h5q7dnee,h5q7dnel,h5q7dnes,h5q7dnez,h5q7dne6,
h5q7dned,h5q7dn7k,h5q7dn7r,h5q7dnld,h5q7dnlk,
h5q7dn7e,h5q7dn7l,h5q7dn7s,h5q7dn7z,vgqsknes,
vgqsknez,nja7sn7e,nja7sn7l,nja7sn7s,nja7sn7z,
nja7sn7k,nja7sn7r,nja7sn7y,woc7en7s,woc7en7z,
woc7en76,woc7en7d,4g5e6nes,4g5e6nez,4g5edne7,
4g5e6ney,4g5e6nl7,4g5e6nle,4g5edne6,4g5edned,
4g5ednek,4g5edney,4g5e6nls,4g5e6nl6,4g5e6nld,
4g5e6nlk,4g5ednls,4g5ednld,4g5e6nss,4g5e6nsz,
4g5e6ns6,4g5e6nsd,4g5e6nsk,4g5e6nsr,4g5e6nsy,
4g5e6nz7,4g5e6nze,4g5ednly,4g5edns7,4g5ednse,
4g5ednsl,4g5ednss,4g5ednsz,4g5ednsd,4g5ednsk,
5hne6nlr,5hne6nlk,ab5szn7l,ab5szn7s,ab5szn7z,
ab5szn7e,ab5szn76,ab5szn7d,ab5szn7k,ab5szn7r,
ab5szn7y,ab5szne7,ab5sznl7,ab5sznle,ab5sznld,
ab5sznlk,f5f7ln7e,f5f7ln7l,f5f7ln7s,f5f7ln7z,
f5f7ln7y,f5f7lne7,f5f7lnee,f5f7lnel,f5f7lne6,
q4flrne7,q4flrnee,i5heen7l,c0q7ln76,c0q7ln7y,
c0q7lne7,a5meknlz,a5meknl6,a5meknsd,a5meknsy,
tt1e7nee,tt1e7nel,tt1e7n7e,tt1e7n7l,tt1e7n7k,
tt1e7n7r,`只是我自己剔除这些条目，08_googlevideo里还有9000sn对应的服务器，不自信，没有敢发请求，自己认为，这就如人生老病死一样，坏死的剔除，大家慢慢的添加，几天就会多起来，正如您提到的，工作量很大，做事还要认证负责，添加的和提出的，我几乎不敢相信脚本自动，都是多方验证，做到精准最大，我在这里上传我精简添加后的08_googlevideo文件，您审查一下，如果认可，由您在总基础做更新，
[08_googlevideo.txt](https://github.com/lennylxx/ipv6-hosts/files/1558470/08_googlevideo.txt)

**Comment by ppoozl** [comment]
手工有空大家一起搞吧

**Comment by lennylxx** [comment]
还有一个问题需要考虑就是有些服务器偶尔会下线，然后过一段时间再上线，如果不保留这些收集来的数据等重新上线之后你还要重新收集。

**Comment by lennylxx** [comment]
写了个脚本，把数据全提取出来了。

**Comment by RomanSmile** [comment]
@lennylxx 
建议您抽出宝贵时间，把google那个表格也做一个更新，那个文件不知道别人怎么看和认为，我本人认为那是一个太有价值的宝贵资料，
另外您尽快做更新，我们方便同步，hosts

**Comment by ppoozl** [comment]
我会经常更新的 把你提到的服务器都处理好。
@lennylxx 能不能直接push到你的分支上

**Comment by roc1010kmt** [comment]
最近的dns汙染和rst干擾很嚴重。該死的牆。

**Comment by lennylxx** [comment]
@ppoozl 我把你加成了协作者，commit message尽量用英文并描述清楚改动。一般来说，一个改动对应一个commit，尽量保证各commit之间互相独立。最后尽量保证不犯错误，测试之后再提交。
