### ISSUE TITLE
为什么coursera视频播放不了？

### ISSUE THREAD

**Issue by MonsterGu** [lennylxx/ipv6-hosts#190]
coursera中课程视频无法播放

**Comment by phy25** [comment]
无法解决，参见 #95

**Comment by LGA1150** [comment]
把 CloudFront 解析到这个 IP 即可 `2600:9000:2012:4400:8:1cb7:c900:93a1`
@phy25

**Comment by kbxu** [comment]
牛逼，楼上 @LGA1150 的work了

**Comment by kbxu** [comment]
2600:9000:2012:4400:8:1cb7:c900:93a1 d3c33hcgiwev3.cloudfront.net
刚更新的hosts似乎还没有这句，照楼上楼上把这句加到hosts里就能看了
