### ISSUE TITLE
Instagram出现了新的cdn

### ISSUE THREAD

**Issue by lychichem** [lennylxx/ipv6-hosts#209]
举个例子：scontent-cdg2-1.cdninstagram.com
目前我这边暂时只抓到这个，不确定有没有其他的，IP是2a03:2880:f21f:c4:face:b00c:0:43fe
又发现一个：instagram.fcgh22-1.fna.fbcdn.net，IP是2001:12e0:803:3b:face:b00c:3333:a3f

**Comment by oneyuan** [comment]
我发现了两个
scontent-lga3-1.cdninstagram.com   2a03:2880:f212:c4:face:b00c:0:43fe
scontent-sin6-2.cdninstagram.com   2a03:2880:f20c:2c4:face:b00c:0:43fe
