### ISSUE TITLE
请考虑能否加上 dl.google.com ？

### ISSUE THREAD

**Issue by DAZUER** [lennylxx/ipv6-hosts#21]
不然全系列Google软件都没法用IDM下载，包括Android SDK。只能用浏览器自带的龟速下载。我自己找出的地址最后测试不可用，希望你能考虑加上，谢谢：）

**Comment by lennylxx** [comment]
[460 行](https://github.com/lennylxx/ipv6-hosts/blob/master/hosts#L460)不是有吗？

**Comment by DAZUER** [comment]
明白了，貌似是IDM不支持IPV6的原因。

**Comment by cnritng** [comment]
用端口代理即可

DAZUER <notifications@github.com>于2015年7月5日 周日 01:29写道：
