### ISSUE TITLE
medium的网站好卡，那位大神能不能添加这个网站的dns。谢谢

### ISSUE THREAD

**Issue by cfchang2838** [lennylxx/ipv6-hosts#213]

**Comment by lychichem** [comment]
2400:cb00:2048:1::6810:787f medium.com
2400:cb00:2048:1::6810:7891 cdn-static-1.medium.com
2400:cb00:2048:1::6810:7991 cdn-images-1.medium.com
2400:cb00:2048:1::6810:7591 glyph.medium.com
自己加进hosts就行，不过可能这站cdn很多

**Comment by cfchang2838** [comment]
效果不错，谢谢
