### ISSUE TITLE
A list of all 53 "0\d-xxx\d" FBCDN nodes

### ISSUE THREAD

**Issue by yescallop** [lennylxx/ipv6-hosts#220]
Recently I had used Censys to search the hosts which have the certificate of "*.whatsapp.net", and 53 of them are located in Facebook, Inc.
Node names are listed [here](https://github.com/scallophosts/hosts/blob/master/FBCDNList.txt)

**Comment by lennylxx** [comment]
Cool, can you share more detail about how to find them? Are you generating the list manually or using a command of censys.

**Comment by yescallop** [comment]
Is it too dangerous to talk here? This method can be used directly to find all available IPv4 hosts with one certificate.

**Comment by yingziwu** [comment]
Zmap scan?

**Comment by tigereno** [comment]
Why it does not work on Wifi in mainland china?

**Comment by phy25** [comment]
@tigereno If you are using Android, that's because your system doesn't support IPv6.

**Comment by tigereno** [comment]
@phy25 thanks for reply. I am using windows 10. This hosts file works great on LAN but on WiFi it Doesn't work at all.
