### ISSUE TITLE
可以针对某个特定的ISP来优化这个hosts吗？

### ISSUE THREAD

**Issue by kyobox** [lennylxx/ipv6-hosts#221]
我发现很多ipv6de地址都是台湾的，似乎速度不如香港那边的好

**Comment by 2378** [comment]
难 国内网络环境复杂 难保证效果

**Comment by lennylxx** [comment]
因为IPv6路由偶尔会变，有时台湾的服务器好一些，有时香港的服务器好一些。可以根据自己的情况使用 update_hosts.py 选择合适的DNS更新一下。
