### ISSUE TITLE
hosts速度问题

### ISSUE THREAD

**Issue by huangwenweia** [lennylxx/ipv6-hosts#223]
不知道为什么用这个hosts，谷歌play下载软件速度极快，大约在2mbs，而在youtube看视频却只有1000多kbps，能提供一下香港的youtube视频地址吗？希望作者继续更新hosts，加油！！！

**Comment by LGA1150** [comment]
并不是你想的那样
YouTube 视频服务器域名和 IP 是一对一的，如果 hosts 里缺了就可能直接播放不了，而不是速度慢
