### ISSUE TITLE
Youtube无法搜索了

### ISSUE THREAD

**Issue by EFCHolla** [lennylxx/ipv6-hosts#224]
youtube可以看视频，但是搜索功能失效了。

**Comment by phy25** [comment]
请尝试在地址栏出现 search 字样后刷新页面，会自动跳转到 `ipv6.google.com/sorry/index*`，在完成人机验证后才能搜索。

**Comment by EFCHolla** [comment]
@phy25 你的方法解决我的问题了，谢谢。

**Comment by zyc199847** [comment]
目测是前几天开会的影响，console里各种error，码率也只有1k多，昨天开始恢复了貌似。
