### ISSUE TITLE
求问大佬，有没有办法把这个hosts转化成surge规则？

### ISSUE THREAD

**Issue by StephenAnboer** [lennylxx/ipv6-hosts#225]
我想放进手机里试试，因为网络支持ipv6，但是不会转化规则，请问大佬有没有什么方法可以转化一下呀？或者能不能同步出一版？

**Comment by Chengcheng-Xiao** [comment]
可以试试https://github.com/kokororin/hosts2surge，但是注释部分需要自己写脚本删除才可以正常。

**Comment by lennylxx** [comment]
抱歉，目前没有这个计划。
