### ISSUE TITLE
New type of fbcdn domain name(s)

### ISSUE THREAD

**Issue by lychichem** [lennylxx/ipv6-hosts#226]
It looks like this: `2a03:2887:ff0b:0:face:b00c:3333:a3f instagram.fsea1-1.fna.fbcdn.net` for instagram and `2a03:2887:ff0b:0:face:b00c:0:a7 scontent.fsea1-1.fna.fbcdn.net` for facebook. Looks like former scontent-[a-z][a-z][a-z][0-9]-[0-9].xx.fbcdn.net domain name and  scontent-[a-z][a-z][a-z][0-9]-[0-9].xx.cdninstagram.net domains are deprecated at leaset at my place. And I believe new domains will be like this: `instagram/scontent.[a-z][a-z][a-z][a-z][0-9]-[0-9].fna.fbcdn.net` . However I don't know how to scan all of them so I have to manually add records when the pictures in instagram are not avalible.
I've used branch https://github.com/lychichem/ipv6-hosts/tree/fbcdn to catch the records by me.

**Comment by lennylxx** [comment]
`sea` in `fsea1` seems to be an IATA code. If we can get the pattern, we can write a script to enumerate the possible domains with [known IATA code ](https://github.com/lennylxx/ipv6-hosts/blob/master/data/iata.txt). We collect these codes in Google's domains, but I think we can reuse them in FB's. 
I will investigate this when I have time.
