### ISSUE TITLE
网速变慢

### ISSUE THREAD

**Issue by dawnlau** [lennylxx/ipv6-hosts#227]
今天下午开始谷歌的网络都变得特别慢，只有两三百 k/s，YouTube 连最不清晰的都卡顿，之前 1080p 秒开的。不知道是什么原因。tracert 了一下，不知道是不是谷歌自己的原因。

```
Tracing route to youtube.com [2404:6800:4008:c06::5d]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  2402:f000:5:9c01::156:1
  2    <1 ms    <1 ms     2 ms  2402:f000:0:278::121
  3    <1 ms    <1 ms    <1 ms  2402:f000:0:248::73
  4    <1 ms    <1 ms    <1 ms  2402:f000:0:424::37
  5    <1 ms    <1 ms    <1 ms  cernet2.net [2001:da8:a0:1002::1]
  6     2 ms     2 ms     1 ms  cernet2.net [2001:da8:a0:1::1]
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9    11 ms    11 ms    11 ms  cernet2.net [2001:252:0:100::2]
 10     *        *        *     Request timed out.
 11   168 ms   173 ms   175 ms  10gigabitethernet13-10.core1.lax2.he.net [2001:470:0:2a2::1]
 12   163 ms   168 ms   194 ms  2001:504:13::210:41
 13   166 ms   162 ms   163 ms  2001:4860:0:110e::14
 14   313 ms     *      312 ms  2001:4860::c:4000:de41
 15   313 ms   339 ms     *     2001:4860::c:4000:e103
 16   330 ms   320 ms   307 ms  2001:4860::c:4000:e43d
 17   315 ms   319 ms   321 ms  2001:4860::2:0:73aa
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28   310 ms   316 ms   312 ms  youtube.com [2404:6800:4008:c06::5d]
```

**Comment by dawnlau** [comment]
另外不太懂为啥要从he.net 经过一下

**Comment by Pacerlyy** [comment]
同问
`通过最多 30 个跃点跟踪
到 www.youtube.com [2404:6800:4008:c07::8a] 的路由:

  1    <1 毫秒   <1 毫秒   <1 毫秒 2402:f000:5:c101::193:1
  2     1 ms     1 ms     1 ms  2402:f000:0:278::121
  3     1 ms     1 ms     1 ms  2402:f000:0:248::73
  4     1 ms    <1 毫秒   <1 毫秒 2402:f000:0:424::37
  5     1 ms     1 ms     1 ms  cernet2.net [2001:da8:a0:1002::1]
  6    16 ms     2 ms     2 ms  cernet2.net [2001:da8:a0:1::1]
  7     *        *       41 ms  2001:da8:1:501::1
  8     *        *        *     请求超时。
  9     1 ms     1 ms     1 ms  cernet2.net [2001:252:0:100::2]
 10     *      189 ms     *     cernet2.net [2001:252:0:302::2]
 11   156 ms   161 ms     *     10gigabitethernet13-10.core1.lax2.he.net [2001:470:0:2a2::1]
 12   161 ms   160 ms   162 ms  2001:504:13::210:41
 13     *        *      158 ms  2001:4860:0:1110::13
 14   158 ms   158 ms   156 ms  2001:4860::c:4000:de40
 15   304 ms   306 ms   308 ms  2001:4860::c:4000:e102
 16   306 ms   310 ms     *     2001:4860::8:0:c70c
 17   312 ms   308 ms   307 ms  2001:4860::2:0:73aa
 18     *        *        *     请求超时。
 19     *        *        *     请求超时。
 20     *        *        *     请求超时。
 21     *        *        *     请求超时。
 22     *        *        *     请求超时。
 23     *        *        *     请求超时。
 24     *        *        *     请求超时。
 25     *        *        *     请求超时。
 26     *        *        *     请求超时。
 27     *        *        *     请求超时。
 28     *      305 ms   305 ms  encrypted-tbn0.google.com [2404:6800:4008:c07::8a]`

**Comment by LGA1150** [comment]
看样子是又绕路了，我先观察几天。你们可以暂时用`hosts_lax`文件，但是 YouTube 慢的问题无法自行解决

**Comment by wy-luke** [comment]
我也遇到了，最担心的就是IPV6被封锁了

**Comment by ppoozl** [comment]
HE 是最大的V6运营商 除非有互联 不然都走HE

**Comment by dawnlau** [comment]
@wy-luke 
不用担心，这个是一定的。
我的 ipv6 的代理这几天变得巨慢，还总断。

**Comment by uiuu123** [comment]
同教育网，youtube网速非常慢。感觉是CNGI出口有问题。

**Comment by foowaa** [comment]
科技网 也是这个情况，youtube非常慢，Gmail也变慢了

**Comment by suzhengpeng** [comment]
同样 y2b 卡死了

**Comment by ifeelok** [comment]
教育网，YouTube变慢了。

**Comment by wy-luke** [comment]
是不是恢复了？

**Comment by uiuu123** [comment]
已恢复到正常速度。

**Comment by suzhengpeng** [comment]
好了两个小时，又不行了

**Comment by Jasper0819X** [comment]
同教育网，走IPv6的VPS始终不超过100k，早上6点左右可以6MB/s，估计是分时段限速

**Comment by dawnlau** [comment]
看来 ipv6 是在垒墙了

**Comment by dawnlau** [comment]
http://www.gov.cn/zhengce/2017-11/26/content_5242389.htm

**Comment by uiuu123** [comment]
现在速度又正常了（23：38）

**Comment by AaarnoldH** [comment]
同教育网，同问题

**Comment by lychichem** [comment]
Gmail的IMAP似乎也分时段封锁了，至少今天白天根本上不去

**Comment by lennylxx** [comment]
建议

**Comment by dawnlau** [comment]
> 建议hosts 和 hosts_lax 切换使用

问下这俩的区别是啥

**Comment by turkey-1** [comment]
同教育网，用hosts_lax看youtube也是一样的慢，几百k或者1000多k，和原来差了几十倍。

**Comment by LGA1150** [comment]
@turkey-1 
这个只能等教育网或 Google 任意一方作出调整，不然还是绕路

**Comment by lychichem** [comment]
> @turkey-1
这个只能等教育网或 Google 任意一方作出调整，不然还是绕路

指望教育网调整不可能的，只能看谷歌了

**Comment by LGA1150** [comment]
已恢复

**Comment by xiuluo** [comment]
别乱猜了，3月底ipv6的限速只是因为"目前cernet2到香港是在cernet是上面跑的 vpn 线路(我猜测是MPLS VPN)，前段时间cernet 那边压力大，所以让 cernet2 撤走了些流量。至于到洛杉矶也慢是因为cernet2国际汇聚有个地方堵住了，所以限制了北美的商业流量。你们可以用到apan的线路，目前apan 还好"。（以上内容均来自某个大佬，我只是个搬运工）
PS：安徽教育网省际出口终于扩容了(https://bbs.ustc.edu.cn/cgi/bbstcon?board=USTCnet&file=M.1522823066.A)，喜大普奔，然而国际出口还是很堵，然并卵。。。
