### ISSUE TITLE
把Github相关的条目取消注释吧

### ISSUE THREAD

**Issue by lychichem** [lennylxx/ipv6-hosts#228]
大概是从今天下午开始，全国范围内Github都进豪华套餐了：http://www.17ce.com/site/ping/201803_15b51e1dd6d5d9e99eb90c234e605ff9.html
我强烈怀疑是昨天谷歌那发布新工具的研究员的锅

**Comment by visualer** [comment]
北京没有问题啊。什么新工具？

**Comment by LGA1150** [comment]
部分运营商到 NTT 的出口炸了而已

**Comment by lychichem** [comment]
@LGA1150 应该是昨天下午短暂性炸了，昨天下午的检测结果全大陆爆炸，今天就好了
