### ISSUE TITLE
如何不通过hosts当网站有Ipv6时优先使用?

### ISSUE THREAD

**Issue by wszgrcy** [lennylxx/ipv6-hosts#229]
感觉既然有Ipv6,那么就应该有优先使用的办法,老这么改Hosts总有一天会和v4一样频繁的被干掉
当然,如果防火墙目前没对v6下手,那么有没有优先使用v6的方法呢?

**Comment by LGA1150** [comment]
原本就是这样的，但你得首先解决DNS污染问题

**Comment by wszgrcy** [comment]
我同时开v4和v6.访问google不通过,但是把v4关了,发现就能访问google了

**Comment by DannyVim** [comment]
我没有这样的问题。本地有host的时候，电脑会优先使用host里面的内容进行连接。所以同时开着v6和v4并不会冲突。 @wszgrcy
