### ISSUE TITLE
是不是Youtube速度又不行了？

### ISSUE THREAD

**Issue by suzhengpeng** [lennylxx/ipv6-hosts#237]
选择最低的分辨率都卡的要死。已经连续好几天了。是不是大家都这样啊？

**Comment by nolitus** [comment]
是的

**Comment by StephenAnboer** [comment]
最近貌似全国的ipv6都被限速了

**Comment by Ambitie** [comment]
没有限速，是谷歌添加了服务器了。IPV6没有限速。用VLC看视频还是可以的

**Comment by ppoozl** [comment]
请问能提供几组添加的服务器吗

**Comment by hallochina** [comment]
术业有专攻，走付费v.pn吧，https://vpnchina.zdhweb.com

**Comment by xuelide** [comment]
我在加拿大···用着1Gbps的网，经常youtube只有1-10Mbps的链接速率，已经快3 4个月了。

**Comment by lennylxx** [comment]
@xuelide 这个项目主要是为了中国大陆用户，IP全是优化过的，你在加拿大当然速度会受影响，为什么不直接连接？

**Comment by xuelide** [comment]
我就是直连速度很慢， 找各种解决方案的时候顺带知道这个项目而已。

另外你说这个项目主要为了中国大陆用户，如果使用了在加拿大会受到影响？但是我看了一下列表，服务器的IP不是就只是各个服务器原本的IP么？ 优化的点在哪里？ 

比如我是用加拿大这边一个叫ROGERS的网，他们有几组缓存服务器，我也都解析过了，IP地址和项目提供的是一样的，这样我添加到hosts里的时候，应该是没有什么影响的吧?直接本地HOSTS不是应该理论上还更快了么。

**Comment by lennylxx** [comment]
@xuelide 建议你了解一下DNS, CDN和Google Global Cache是如何工作的再来反驳我。这只是一个开源项目，我觉得好，分享给大家，而且我也注明了Mainland China only，你愿意在加拿大使用我管不着，但是请不要在这个issue里贴无效的信息，因为在我看来加拿大和本项目无关。

**Comment by wslyh8** [comment]
您好，L大，感谢您的项目帮助。我使用win10，现在使用您的hosts可以通过ipv6访问 google.com ，可是无法打开 Youtoube ，不知道是我哪里设置不对，请指导下。感恩。
