### ISSUE TITLE
Can't connect to YouTube anymore

### ISSUE THREAD

**Issue by harrylaw** [lennylxx/ipv6-hosts#244]
连不上YouTube了

**Comment by koolwiki** [comment]
Me too, started from yesterday.

**Comment by myjlpt** [comment]
一样，昨天开始。但IPV6 上使用代理依旧速度。IPV4下代理速度惨淡。

**Comment by masktao** [comment]
我这边正常,很正常,手机在路由下用host,畅通

**Comment by myjlpt** [comment]
@masktao 地区 运营商不一样，是有很大差别的

**Comment by masktao** [comment]
@myjlpt 是的,我这边反而dropbox上不去

**Comment by masktao** [comment]
是不是该更新一下了,现在ins死翘翘了

**Comment by myjlpt** [comment]
几乎全死了。连GOOGLE搜索都挂了
