### ISSUE TITLE
请添加一些谷歌play音乐stream服务器域名

### ISSUE THREAD

**Issue by shuangzhijinghua** [lennylxx/ipv6-hosts#25]
sj.googleusercontent.com
还有类似
r1---sn-i3b7knel.c.doc-0-0-sj.sj.googleusercontent.com
这样的域名，使用谷歌play音乐客户端的时候就会从这些服务器获取音频流（居然使用gws的服务器唉）。
这些域名是在shadowsocks服务器上抓包查看SNI标签得到的，客户端连接的这些IP是在与谷歌服务器通讯的时候直接传送给客户端，故无DNS请求只看到IP连接。
另外还有一个Googlenow的邮件查看功能里面那个Gmail的LOGO也是如此，客户端直接连接IP而没有DNS查询动作。后面补上。

**Comment by shuangzhijinghua** [comment]
mts1.googleapis.com
mts0.googleapis.com
请添加.
mts9.googleapis.com也可以查询到，不过日常使用只会用到0-3。

**Comment by lennylxx** [comment]
r1---sn-i3b7knel.c.doc-0-0-sj.sj.googleusercontent.com
这样的域名前面的编码是统一的，只有域不同。Google 应该用的是自动匹配的方法，如果全部添加的话，会增加非常多条 hosts，文件会变得非常大。

其他几个会添加。

**Comment by shuangzhijinghua** [comment]
mua1.googleusercontent.com
mua2.googleusercontent.com
mua3.googleusercontent.com
mua4.googleusercontent.com
mua5.googleusercontent.com
mua6.googleusercontent.com
mua7.googleusercontent.com
mua8.googleusercontent.com
mua9.googleusercontent.com
mua1.ggpht.com
mua2.ggpht.com
mua3.ggpht.com
mua4.ggpht.com
mua5.ggpht.com
mua6.ggpht.com
mua7.ggpht.com
mua8.ggpht.com
mua9.ggpht.com
apidata.googleusercontent.com
请添加。

**Comment by lennylxx** [comment]
最后一个可以查到，前几个是干什么用的？

**Comment by shuangzhijinghua** [comment]
google play音乐的图片加载地址。

**Comment by lennylxx** [comment]
```
$ dig @tserv1.lax1.he.net mua1.ggpht.com aaaa +vc

; <<>> DiG 9.8.3-P1 <<>> @tserv1.lax1.he.net mua1.ggpht.com aaaa +vc
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 13047
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;mua1.ggpht.com.			IN	AAAA

;; AUTHORITY SECTION:
ggpht.com.		600	IN	SOA	ns1.google.com. dns-admin.google.com. 100573204 21600 3600 1038800 60

;; Query time: 245 msec
;; SERVER: 66.220.18.42#53(66.220.18.42)
;; WHEN: Thu Aug 13 23:42:53 2015
;; MSG SIZE  rcvd: 89
```

根本查不到，是不是写错了？

**Comment by shuangzhijinghua** [comment]
我这里能查到的基本是mua3系列，可以只添加它。

lennylxx <notifications@github.com>于2015年8月13日周四 下午11:44写道：
