### ISSUE TITLE
emmm求问pornhub是不是上不去呢...

### ISSUE THREAD

**Issue by fjh1223kobe** [lennylxx/ipv6-hosts#254]
emmmm

**Comment by jamiechoi1995** [comment]
我也上不去了

**Comment by fjh1223kobe** [comment]
好像的确是没有给它分配地址，但是需要怎么来对一个新的网站自己加IP地址呢？看内个DIY没有看太明白

**Comment by lennylxx** [comment]
Please do not post any content related to pornography, or you will be blocked.
https://help.github.com/articles/github-terms-of-service/#2-content-restrictions

**Comment by fjh1223kobe** [comment]
i am sorry, will not do that again
