### ISSUE TITLE
运行脚本遇到 dig 相关错误

### ISSUE THREAD

**Issue by DannyVim** [lennylxx/ipv6-hosts#255]
PC 是 WIN10 系统。
运行脚本的时候遇到错误：

> It seems you don't have 'dig' command installed properly on your system.

第一次遇到错误之后安装好了`dig`，但是再运行的时候还是提示这个错误。请问，是什么地方需要进行一定的修改嘛？

**Comment by StevenHolmes** [comment]
Windows下显然不能跑这个脚本，你可以用win10的linux子系统试试看
（不过我跑了脚本也没有什么用，大概是运营商封的太严了...）

**Comment by hujy23** [comment]
windows里恐怕无法运行。

这个问题，只需要删掉代码里判断dig位置的那几行就行。

后面还会遇到更多问题，第155行select.select()那里还会报一个错，放弃了。(Github竟然不会自动保存草稿，Win10搞崩了，重启了懒得去Win10了）

在Win10子系统跑吧，或者其他Linux、Mac里跑～

**Comment by lennylxx** [comment]
The script doesn't support to be executed on Windows.
