### ISSUE TITLE
Can't load reCAPTCHA Verification while searching in YouTube

### ISSUE THREAD

**Issue by zhouym233** [lennylxx/ipv6-hosts#258]
It looks like that.
![screenshot](https://user-images.githubusercontent.com/26868483/45830667-35977b80-bd30-11e8-8442-d42f678016e2.jpg)

**Comment by lennylxx** [comment]
Can you provide more detail information? like[ Developer Tools](https://developers.google.com/web/tools/chrome-devtools/) Network tab. 
Which URL can't be accessed?
I don't know whether others can reproduce this, can you share repro steps?

**Comment by YanminZhou** [comment]
My step: I just open Youtube home page,type in Searching Bar and press Enter.
Under normal circumstances, it should be a verification.
![normal](https://user-images.githubusercontent.com/26868483/46157737-f37db500-c2ae-11e8-99a2-fa96f2e627f7.png)
Now it seems entered an Infinite loop. 
![1](https://user-images.githubusercontent.com/26868483/46157959-769f0b00-c2af-11e8-8097-81378b1333fd.jpg)
And there are 503 errors:
![5](https://user-images.githubusercontent.com/26868483/46157977-80c10980-c2af-11e8-88e4-4766455a5e8d.jpg)
I think you may need the .har file:
[www.google.com.har.zip](https://github.com/lennylxx/ipv6-hosts/files/2424812/www.google.com.har.zip)
Many of my schoolmates have found the same problems. It may appeared in 2 or 3 months ago.
Thank You.

**Comment by phy25** [comment]
The reason of your issue is that https://www.google.com/recaptcha/api2/anchor cannot load and causes an infinite redirect loop to https://www.google.com/sorry. This seems like Google's server issue, and you can try changing its hosts IP (other server may work correctly).
