### ISSUE TITLE
大佬能不能增加dnsmasq 

### ISSUE THREAD

**Issue by haygcao** [lennylxx/ipv6-hosts#259]
大佬能不能添加dnsmasq 格式的 ，谢谢大佬

**Comment by LGA1150** [comment]
dnsmasq 本身就支持读取 hosts

**Comment by lennylxx** [comment]
This seems to work.
https://askubuntu.com/questions/117899/configure-networkmanagers-dnsmasq-to-use-etc-hosts
Search the Internet before you open an issue.
