### ISSUE TITLE
fonts.googleapis.com似乎可以加速？

### ISSUE THREAD

**Issue by XIAOSpider97** [lennylxx/ipv6-hosts#26]
nslookup fonts.googleapis.com 240c::6666
我得到这些IP：
240c:f:1:5000:64:0:cbd0:308x（x=0-9）
但似乎也不是AS15169...

**Comment by lennylxx** [comment]
http://www.tcpiputils.com/browse/ipv6-address/240c:f:1:5000:64:0:cbd0:3080
看样子 IP 属于国内一家公司，`240c::6666` 也是这家公司的 DNS。
也许是做了反代？

**Comment by XIAOSpider97** [comment]
这是六飞的母公司，天地互连。

**Comment by lennylxx** [comment]
不是 Google 的 IP，大家可能会担心安全性，自己用的话倒是没问题。

**Comment by LGA1150** [comment]
看起来是一个NAT64服务器
前缀为 240c:f:1:5000:64::/96
因此真实的IPv4应为 203.208.48.128-137
