### ISSUE TITLE
希望可以支持archive.org

### ISSUE THREAD

**Issue by cloudskytian** [lennylxx/ipv6-hosts#262]
先谢谢作者的辛勤工作了
archive.org这个网站是互联网档案馆，还是很好用的，希望可以支持一下
顺便，推特的hosts失效了，希望可以更新或者删除

**Comment by lychichem** [comment]
推没有开放IPV6（目前）。所以更新是不可能更新的。如果推的服务器和本机上了tls1.3的话这些IP可能还能抢救一下，可能这是还没删除的原因吧
archive.org也没有IPV6，你看看IPV4能不能用吧：`207.241.224.2`
