### ISSUE TITLE
最近只有Youtube能正常浏览

### ISSUE THREAD

**Issue by Zebra-zzzz** [lennylxx/ipv6-hosts#272]
尝试了几个Google的网站，应用商店、gmail、youtube可以正常打开，其他Goole的网站（主要是google搜索）没有响应，想问问是我的问题吗Orz，谢谢！

**Comment by dadaewqq** [comment]
一言以蔽之，是。（🌸🐔）

**Comment by Zebra-zzzz** [comment]
那可能是宿舍ipv6的问题...教学楼的DIVI是没有问题的Orz

**Comment by dadaewqq** [comment]
删掉hosts换几个dns试试

**Comment by dadaewqq** [comment]
😂老哥清华的么？那挺好的嘛 tuna的dns就很好

**Comment by Zebra-zzzz** [comment]
Tuna也有啊！我不太懂这些Orz...研究一下，我以前都是直接改的hosts

**Comment by Zebra-zzzz** [comment]
删了hosts换成Tuna的DNS了，还是不行，明天问问同学吧Orz

**Comment by Zebra-zzzz** [comment]
现在Google访问正常了！谢谢呀！

（虽然Wikipedia还是不行...需要时还是翻墙吧

**Comment by dadaewqq** [comment]
不知道啥问题 不觉我觉得这hosts和dns挺好用的 （坐标西安(～￣▽￣)～ ）

**Comment by Zebra-zzzz** [comment]
hosts用了一年多真的很好用！就是最近宿舍这边就是时断时续的，应该是宿舍的问题，室友的ipv6直接不能上了，有线很多宿舍也不能用了
