### ISSUE TITLE
部分Microsoft系的IP不好用

### ISSUE THREAD

**Issue by lychichem** [lennylxx/ipv6-hosts#274]
比如现有的IP在我这里的环境下Windows 10应用商店基本没法更新/下载应用。找了点新的IP（使用你readme那个he的DNS）：
<code>2001:4de0:4008:1b2::356e www.microsoft.com #e13678.dspb.akamaiedge.net   

2001:4de0:4008:197::2886 i.microsoft.com #e10374.dscg.akamaiedge.net   

2001:4de0:4008:197::2886 i2.microsoft.com #i.microsoft.com.edgekey.net   

2001:4de0:4008:197::2886 i3.microsoft.com #i.microsoft.com.edgekey.net   

2002:836b:9820::836b:9886 www.ipv6.microsoft.com   

2001:4de0:4008:19e::e59 download.microsoft.com #e3673.dscg.akamaiedge.net   

2606:2800:11f:7de:d31:7db:168f:1225 download.visualstudio.microsoft.com #cs10.wpc.v0cdn.net   

2001:4de0:ac10::1:1:19 download.windowsupdate.com #cds.d2s7q6s2.hwcdn.net   

2001:4de0:ac19::1:b:1a dl.delivery.mp.microsoft.com #tlu.dl.delivery.mp.microsoft.com.bsgslb.cn   

2600:1401:5::6864:5d10 tlu.dl.delivery.mp.microsoft.com #a1856.dspw65.akamai.net   

#2400:a980:ff:f9::2:3 8.tlu.dl.delivery.mp.microsoft.com #tlu.dl.delivery.mp.microsoft.com.bsgslb.cn   

2001:438:fffd:98::4 10.tlu.dl.delivery.mp.microsoft.com #zstore.v.bsgslb.cn<code>

**Comment by lennylxx** [comment]
抱歉我已经没有IPv6网络很久了。如果你觉得这些IP可用，可以帮到其他人，欢迎发PR，我会merge到master。Thanks

**Comment by lychichem** [comment]
>           的确，会导致微软应用商店无法下载，我花了好多时间来解决，最后我决定将所有Microsoft条目注释掉，毕竟访问微软一边情况下没有什么问题。

未必，我这里可能运营商对akamai有什么策略，微软的一些用了akamai cdn的页面无法加载完全。我手上找到了一些域名和ip，但是还不想太早放出来（主要是没找全以及没确认所有环境下的有效性）

**Comment by Ynewtime** [comment]
同上述情况，在使用 ipv6-host 的情况下无法下载微软应用和进行更新

**Comment by lychichem** [comment]
@Sword-Destiny @Ynewtime 你们二位用我上面贴出来的那些IP替换试试看能用吗？能用我就提交了

**Comment by Ynewtime** [comment]
> 
> 
> @Sword-Destiny @Ynewtime 你们二位用我上面贴出来的那些IP替换试试看能用吗？能用我就提交了

嗯，上面的 ip 可以 ping 通

**Comment by lychichem** [comment]
@Ynewtime 能ping通不代表能用，你先测试下真实环境中可不可使用，只看ping没用的，毕竟有tls rst这种东西存在，基于icmp的ping没法判断的，除非你tcp ping

**Comment by Ynewtime** [comment]
下载速度有点慢，算是能用吧

**Comment by Shuguberu** [comment]
我也是发现了这个问题

**Comment by lychichem** [comment]
#281 尝试修复了这块，各位受影响的可以先试试看好不好用
