### ISSUE TITLE
今天突然不能访问Google了(其他网站例如youtube可以访问)，大家的情况如何呢？

### ISSUE THREAD

**Issue by Feiyu-Zhang** [lennylxx/ipv6-hosts#276]

**Comment by Junyangz** [comment]
Maybe you are in CSTNET not CERNET2. IPv6 route is boom here.
Try `traceroute6 google.com`

**Comment by lczxxx123** [comment]
> Maybe you are in CSTNET not CERNET2. IPv6 route is boom here.
> Try `traceroute6 google.com`

无法理解为什么把这两个网给限制了……

**Comment by huguyuehuhu** [comment]
@Feiyu-Zhang 现在是不是 在 CASIA的 网络，都不能用这种方式连接了，同CASIA....

**Comment by dongxiao92** [comment]
同CAS表示这个封的真是莫名其妙

**Comment by Sword-Destiny** [comment]
> Maybe you are in CSTNET not CERNET2. IPv6 route is boom here.
> Try `traceroute6 google.com`

cstnet不是很早就支持ipv6吗，为什么突然就挂了。

**Comment by Christinmartin** [comment]
CAS表示ipv6无法正常用了

**Comment by xiamr** [comment]
墙开始搞IPv6地址封锁了，这个ipv6的方法在中科院也失效了。不过应该漏网之鱼，希望此项目能够做一下还能用的一些地址的整理

**Comment by fushengzhijushi** [comment]
表示今天上午还可以用，下午大概5点办的时候突然不能用了

**Comment by StephenAnboer** [comment]
我昨天晚上突然不能用的，不知道是咋回事儿

**Comment by lujg** [comment]
通过traceroute追踪路由，第一个是到Google的路由，第二个是一个国外服务器的路由(出口和入口省略了部分信息）
```
到 google.com [2404:6800:4008:c00::71] 的路由:
  1     *        *        3 ms  2402:f000:1:1501:0xx
  2     1 ms     1 ms     4 ms  2402:f000:0:3cc::206
  3     1 ms     1 ms    <1 毫秒 2402:f000:0:288::137
  4     1 ms     1 ms     1 ms  2402:f000:0:424::37
  5     1 ms     1 ms     1 ms  cernet2.net [2001:da8:a0:1001::1]
  6     1 ms     1 ms     1 ms  2001:da8:2:101::1
  7     *        *        *     请求超时。
  8     *        *        *     请求超时。
后面都是请求超时
```
```
通过最多 30 个跃点跟踪
到 2607-8700-xx 的路由:
  1     *        1 ms     *     2402:f000:1:1501:0xx
  2    <1 毫秒    1 ms    <1 毫秒 2402:f000:0:3cc::206
  3     1 ms     1 ms     1 ms  2402:f000:0:288::137
  4     1 ms     1 ms     1 ms  2402:f000:0:424::37
  5     1 ms     1 ms     1 ms  cernet2.net [2001:da8:a0:1001::1]
  6     1 ms     1 ms     1 ms  2001:da8:2:101::1
  7     *        *        *     请求超时。
  8     1 ms     6 ms     1 ms  cernet2.net [2001:252:0:100::2]
  9     *        *        *     请求超时。
 10   261 ms   255 ms   263 ms  10gigabitethernet13-10.core1.lax2.he.net [2001:470:0:2a2::1]
 11   262 ms   264 ms   260 ms  2001:504:13::210:159
 12   288 ms   281 ms   272 ms  2607:fcd0:100:5::2f
 13   251 ms   262 ms   266 ms  2607:fcd0:100:5::2
 14   285 ms   276 ms   256 ms  2607-8700-xx
 15   239 ms   236 ms   237 ms  2607-8700-xx
```

**Comment by AzureStar5** [comment]
昨天下午不能用了，然后就一直不行了。之前也有过几次连不上的情况，不过半天后就又能用了，这次可能是真的封了。

**Comment by MarcusMogg** [comment]
我也是突然不能用Google
```
正在 Ping google.com [2404:6800:4008:c00::71] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

2404:6800:4008:c00::71 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，
```
但我删了hosts之后就可以用了

```
正在 Ping google.com [2404:6800:4005:801::200e] 具有 32 字节的数据:
来自 2404:6800:4005:801::200e 的回复: 时间=40ms
来自 2404:6800:4005:801::200e 的回复: 时间=40ms
来自 2404:6800:4005:801::200e 的回复: 时间=40ms
来自 2404:6800:4005:801::200e 的回复: 时间=40ms

2404:6800:4005:801::200e 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 40ms，最长 = 40ms，平均 = 40ms
```
是不是hosts里面的地址已经gg，该换了
gmail之类的也是这样

**Comment by Elaboration12138** [comment]
教育网可以直接上Google，但是别的都上不去了，可能就是被土蔷了

**Comment by ICHx** [comment]
這裏也是校園網，同樣問題

**Comment by Elaboration12138** [comment]
寻找新的工具吧。果然推广IP v6的前提是建好墙

**Comment by leopoldwannabeinternational** [comment]
YouTube和Google在天津ipv6已经都跪了，只剩Google scholar可以正常打开

**Comment by Elaboration12138** [comment]
VPN好像也只有express能用了吧

**Comment by LGA1150** [comment]
原来墙都部署到中科院了，看来我还是太天真了
呵呵

**Comment by Elaboration12138** [comment]
教育网还是可以上Google的，别的全崩

**Comment by Elaboration12138** [comment]
通过最多 30 个跃点跟踪
到 google.com [2404:6800:4008:802::200e] 的路由:

  1     2 ms     2 ms     2 ms  2001:da8:208:8823::1
  2     2 ms     1 ms     1 ms  2001:da8:208:2000::281
  3     1 ms     1 ms     1 ms  2001:da8:208::22
  4    <1 毫秒    1 ms    <1 毫秒 cernet2.net [2001:da8:ad:3212::1]
  5    20 ms     6 ms     2 ms  cernet2.net [2001:da8:ad:1000::1]
  6    <1 毫秒   <1 毫秒   <1 毫秒 cernet2.net [2001:da8:ad:4::1]
  7     1 ms     1 ms     1 ms  2001:da8:2:123::1
  8    16 ms     1 ms     1 ms  2001:da8:2:5::1

**Comment by alanfoxye** [comment]
sigh, 教育网IPv6油管谷歌全跪，facebook意料之外情理之中的没跪（看来还是小扎同学有点眼力劲儿）。。。。。。

**Comment by lychichem** [comment]
不能用的自己动手想想办法，readme写的很清楚了。我这里正在自己恢复，但是考虑个人安全我就不发了

**Comment by huangwenweia** [comment]
可以试试自己生成hosts，把需要的dns换为240c::666

**Comment by AzureStar5** [comment]
Google和YouTube已经恢复了，可能跟习大大访问某所高校有关吧

**Comment by ICHx** [comment]
先把 #withgoogle.com 前面所有entry 删掉用着，这样可以继续用油罐

**Comment by xiamr** [comment]
google ipv6 dns 都在CAS跪了，搞不明白搞DNS干嘛

**Comment by huangwenweia** [comment]
试试这个https://github.com/huangwenweia/available-ipv6-hosts

**Comment by lychichem** [comment]
Google Scholar突然解析不出IPV6 IP了，然后不出意外跪了，大家情况如何

**Comment by Lynchie** [comment]
教育网删掉DNS还能搜索，ytb上不去了

**Comment by lychichem** [comment]
Wikipedia也全挂了

**Comment by RayinTHU** [comment]
从1月13日开始，直到现在。
THU里面有的能上Google，有的不能上Google，Ytb基本不能登陆。貌似上周17日下午出现了短暂的正常半小时，可以正常访问google和Ytb，四点之后便再也连不上了...
BYRbt依然正常，但是BYR-IPTV卡得根本没法看，播一下卡一下。。。感觉整个人都不好了...

**Comment by huangwenweia** [comment]
> 从1月13日开始，直到现在。
> THU里面有的能上Google，有的不能上Google，Ytb基本不能登陆。貌似上周17日下午出现了短暂的正常半小时，可以正常访问google和Ytb，四点之后便再也连不上了...
> BYRbt依然正常，但是BYR-IPTV卡得根本没法看，播一下卡一下。。。感觉整个人都不好了...

可能是30周年吧/滑稽

**Comment by RayinTHU** [comment]
> > 从1月13日开始，直到现在。
> > THU里面有的能上Google，有的不能上Google，Ytb基本不能登陆。貌似上周17日下午出现了短暂的正常半小时，可以正常访问google和Ytb，四点之后便再也连不上了...
> > BYRbt依然正常，但是BYR-IPTV卡得根本没法看，播一下卡一下。。。感觉整个人都不好了...
> 
> 可能是30周年吧/滑稽

想到之前GitHub都被墙过，就开始一直焦虑。。。

**Comment by huangwenweia** [comment]
> > > 从1月13日开始，直到现在。
> > > THU里面有的能上Google，有的不能上Google，Ytb基本不能登陆。貌似上周17日下午出现了短暂的正常半小时，可以正常访问google和Ytb，四点之后便再也连不上了...
> > > BYRbt依然正常，但是BYR-IPTV卡得根本没法看，播一下卡一下。。。感觉整个人都不好了...
> > 
> > 
> > 可能是30周年吧/滑稽
> 
> 想到之前GitHub都被墙过，就开始一直焦虑。。。

我觉得应该是什么【特殊时期】，等过段时间再看看吧

**Comment by Sword-Destiny** [comment]
CSTNET可以正常访问谷歌了，可能是前一段时间在建设ipv6吧😀

**Comment by yintianyu** [comment]
> CSTNET可以正常访问谷歌了，可能是前一段时间在建设ipv6吧😀

用哪个hosts?Y能看视频吗

**Comment by yintianyu** [comment]
> > CSTNET可以正常访问谷歌了，可能是前一段时间在建设ipv6吧😀
> 
> 用哪个hosts?Y能看视频吗

我现在能上Y和G但是视频看不了

**Comment by zbhfut** [comment]
IPV6改DNS可上G，但Y始终打不开，改hosts不管用

**Comment by NINGNINGGAO** [comment]
> 不能用的自己动手想想办法，readme写的很清楚了。我这里正在自己恢复，但是考虑个人安全我就不发了
试了一遍，还是不能用啊

**Comment by Sean16SYSU** [comment]
试下我在用的这份？
https://github.com/Sean16SYSU/ipv6-dns
