### ISSUE TITLE
上不了youtube，twitter

### ISSUE THREAD

**Issue by Hui-Se** [lennylxx/ipv6-hosts#278]
突然上不了youtube和twitter了，肿磨破

**Comment by dadaewqq** [comment]
Twitter本来就上不了吧。。

**Comment by Hui-Se** [comment]
Google可以上的

**Comment by kevindanielucas** [comment]
现在是YouTube，Google都上不去了，甚至连北邮人都打不开，应该是ipv6的问题。

**Comment by Jackli9218** [comment]
大家Google都上不去了吗？

**Comment by Washakh** [comment]
did anyone find any solution?

**Comment by lennylxx** [comment]
缺少有效信息，下次请提供自己的网络环境，并给出自己尝试的步骤和自己问题的详细描述。
