### ISSUE TITLE
两三天前整个外网都无法访问了，看起来ipv6也将被干掉了。。。so sad

### ISSUE THREAD

**Issue by Sword-Destiny** [lennylxx/ipv6-hosts#279]
能有办法解决吗？

**Comment by Washakh** [comment]
Did you find any solution bro?

**Comment by lennylxx** [comment]
https://github.com/lennylxx/ipv6-hosts/issues/278  https://github.com/lennylxx/ipv6-hosts/issues/280 重复，且缺少有效信息。
