### ISSUE TITLE
Not Working in China since the past two days

### ISSUE THREAD

**Issue by Washakh** [lennylxx/ipv6-hosts#280]
Not working in China since the past two days, any updates?

**Comment by dadaewqq** [comment]
Come on！  Join the CERTNET～

**Comment by Washakh** [comment]
>           Come on！  Join the CERTNET～

what's that?

**Comment by dadaewqq** [comment]
教育网！

**Comment by lennylxx** [comment]
https://github.com/lennylxx/ipv6-hosts/issues/278 重复，且缺少有效信息。
