### ISSUE TITLE
hosts挂掉了

### ISSUE THREAD

**Issue by Alaife** [lennylxx/ipv6-hosts#282]
具体一点是1月15日，未全部排查，但是google和youtube全都断了

**Comment by scdlzdh** [comment]
now instagram is dead too.

**Comment by NeverKnowsTomorrow** [comment]
教育网用户，这两天也是用hosts上不了Google和YouTube，但hosts注释掉或者删掉ipv6地址，可以直接上Google和YouTube，我这里是这样

**Comment by FrankScarlet** [comment]
同教育网...15号左右开始，Google和Youtube 不行，Instagram能正常访问

**Comment by xiangweigeng** [comment]
天津教育网，现在已经可以用了。

**Comment by NeverKnowsTomorrow** [comment]
天津教育网，可以用了。现在是hosts修不修改都可以上Google，YouTube，相当于没有墙了

**Comment by BBBob** [comment]
北京教育网，昨晚一小段时间可以无墙直连

**Comment by congx961** [comment]
武汉教育网 挂了

**Comment by NeverKnowsTomorrow** [comment]
现在是使用hosts文件的情况下，有时候连不上，但是不用hosts文件时一直能连上

**Comment by congx961** [comment]
武汉教育网 使用hosts上不了 不使用hosts只能上一部分

**Comment by ICHx** [comment]
https://github.com/lennylxx/ipv6-hosts/issues/276

**Comment by BITTaoge** [comment]
> 北京教育网，目前无需主机，可以直连

北京教育网 不使用hosts可以上google ，但是youtube打不开 使用hosts 都打不开

**Comment by BigMangos** [comment]
不用hosts 暂时G/Y都可以

**Comment by l00c00l** [comment]
也是这周突然不能访问G,Y
更新了这里的hosts，也不行
能看到大家的实时通报，真好....

**Comment by l00c00l** [comment]
不用host，可以访问google! y2b不行

**Comment by ChiChiNianNian** [comment]
> 现在是使用hosts文件的情况下，有时候连不上，但是不用hosts文件时一直能连上
不用hosts的时候，有时候上不去，同天津教育网

**Comment by huangwenweia** [comment]
试试这个hosts：https://github.com/huangwenweia/available-ipv6-hosts

**Comment by ChiChiNianNian** [comment]
> 试试这个hosts：https://github.com/huangwenweia/available-ipv6-hosts

还是不行

**Comment by huangwenweia** [comment]
> > 试试这个hosts：https://github.com/huangwenweia/available-ipv6-hosts
> 
> 还是不行

我这可以啊

**Comment by huangwenweia** [comment]
@ChiChiNianNian 两个都不行？

**Comment by N3verL4nd** [comment]
dig TXT +short _netblocks{,2,3}.google.com | tr ' ' '\n' | grep '^ip6:' | sed 's/ip6://'

2001:4860:4000::/36
2404:6800:4000::/36
2607:f8b0:4000::/36
2800:3f0:4000::/36
2a00:1450:4000::/36
2c0f:fb50:4000::/36

**Comment by nebula0723** [comment]
教育网用原生的hosts就可以上了(1kb那个)

**Comment by BITTaoge** [comment]
> 试试这个主机：[https](https://github.com/huangwenweia/available-ipv6-hosts)：[//github.com/huangwenweia/available-ipv6-hosts](https://github.com/huangwenweia/available-ipv6-hosts)

可以用 谢谢

**Comment by Loycine** [comment]
> > 试试这个主机：[https](https://github.com/huangwenweia/available-ipv6-hosts)：[//github.com/huangwenweia/available-ipv6-hosts](https://github.com/huangwenweia/available-ipv6-hosts)
> 
> 可以用 谢谢

依旧是只能Google  不能Youtube

**Comment by huangwenweia** [comment]
> > > 试试这个主机：[https](https://github.com/huangwenweia/available-ipv6-hosts)：[//github.com/huangwenweia/available-ipv6-hosts](https://github.com/huangwenweia/available-ipv6-hosts)
> > 
> > 
> > 可以用 谢谢
> 
> 依旧是只能Google 不能Youtube

在5:30PM左右我这也上不了ytb了，我现在试试更新地址

**Comment by Lynchie** [comment]
好像据说是台湾的4008服务器不知道怎么失效了，换香港或者新加坡的其他服务器地址吧

**Comment by hwongbaul** [comment]
> > > > 试试这个主机：[https](https://github.com/huangwenweia/available-ipv6-hosts)：[//github.com/huangwenweia/available-ipv6-hosts](https://github.com/huangwenweia/available-ipv6-hosts)
> > > 
> > > 
> > > 可以用 谢谢
> > 
> > 
> > 依旧是只能Google 不能Youtube
> 
> 在5:30PM左右我这也上不了ytb了，我现在试试更新地址

G可以，但是YTB仍然不行

**Comment by huangwenweia** [comment]
> > > > > 试试这个主机：[https](https://github.com/huangwenweia/available-ipv6-hosts)：[//github.com/huangwenweia/available-ipv6-hosts](https://github.com/huangwenweia/available-ipv6-hosts)
> > > > 
> > > > 
> > > > 可以用 谢谢
> > > 
> > > 
> > > 依旧是只能Google 不能Youtube
> > 
> > 
> > 在5:30PM左右我这也上不了ytb了，我现在试试更新地址
> 
> G可以，但是YTB仍然不行

能访问YTB却不能看视频吗？

**Comment by hwongbaul** [comment]
> > > > > > 试试这个主机：[https](https://github.com/huangwenweia/available-ipv6-hosts)：[//github.com/huangwenweia/available-ipv6-hosts](https://github.com/huangwenweia/available-ipv6-hosts)
> > > > > 
> > > > > 
> > > > > 可以用 谢谢
> > > > 
> > > > 
> > > > 依旧是只能Google 不能Youtube
> > > 
> > > 
> > > 在5:30PM左右我这也上不了ytb了，我现在试试更新地址
> > 
> > 
> > G可以，但是YTB仍然不行
> 
> 能访问YTB却不能看视频吗？

是的，我在你的repo里提了issue

**Comment by zqcSplatoon** [comment]
北京教育网不用hosts只能上google上不了youtube。

**Comment by SriChen2017** [comment]
> 试试这个hosts：https://github.com/huangwenweia/available-ipv6-hosts

陕西教育网可以用，谢谢！

**Comment by huangwenweia** [comment]
> 北京教育网不用hosts只能上google,youtube看不了视频。

同，我科教网页只能上ytb看不了视频

**Comment by suzhengpeng** [comment]
西安 已挂 o(╯□╰)o youtube能打开但是无法播放视频

**Comment by pjgao** [comment]
江苏教育网同不用hosts只能上google,youtube看不了视频。用host连google都不行

**Comment by masktao** [comment]
天啊,都是教育网用户,电信有人理吗?

**Comment by masktao** [comment]
> 试试这个hosts：https://github.com/huangwenweia/available-ipv6-hosts

这里面三个文件,用了两个vimeo完全无法访问,用原本的至少还能访问

**Comment by huangwenweia** [comment]
> > 试试这个hosts：https://github.com/huangwenweia/available-ipv6-hosts
> 
> 这里面三个文件,用了两个vimeo完全无法访问,用原本的至少还能访问

i will rebuild it later

**Comment by delick** [comment]
YouTube能浏览，但是不能播放视频。然后突然账号登陆状态丢失了。现在YouTube主页上什么按钮都点不开。

**Comment by royccg** [comment]
> YouTube能浏览，但是不能播放视频。然后突然账号登陆状态丢失了。现在YouTube主页上什么按钮都点不开。

北京教育网，+1

**Comment by finn-z** [comment]
> YouTube能浏览，但是不能播放视频。然后突然账号登陆状态丢失了。现在YouTube主页上什么按钮都点不开。

解决方法：右键->新窗口打开

**Comment by delick** [comment]
> > YouTube能浏览，但是不能播放视频。然后突然账号登陆状态丢失了。现在YouTube主页上什么按钮都点不开。
> 
> 解决方法：右键->新窗口打开

新窗口是可以打开页面，但是视频和账号登陆还是不行。

**Comment by finn-z** [comment]
> > > YouTube能浏览，但是不能播放视频。然后突然账号登陆状态丢失了。现在YouTube主页上什么按钮都点不开。
> > 
> > 
> > 解决方法：右键->新窗口打开
> 
> 新窗口是可以打开页面，但是视频和账号登陆还是不行。点击登陆后提示：
> `ERR_CONNECTION_TIMED_OUT`
更新下试试，我这边测试登录正常的
https://raw.githubusercontent.com/huangwenweia/available-ipv6-hosts/master/hosts-build-by-tsinghuaDNS

**Comment by Tachyu** [comment]
G也上不去了。。。Y可以打开页面不能播放

**Comment by huangwenweia** [comment]
> 感谢新提供的 googlevideo 地址。不过对很多人来说要命的是 scholar 上不去了

说实话我提供了googlevideo地址也不知道咋搞了，我这边的话老是分配到香港的节点上去，我得想想怎么才能代理到我列表可以用的节点上

**Comment by GeorgeYang95** [comment]
> 感谢新提供的 googlevideo 地址。不过对很多人来说要命的是 scholar 上不去了

scholar & google 上不去 这俩比较要命，其他还好。

**Comment by wtx626** [comment]
用了最新的hosts，scholar & google 还是上不去

**Comment by NeverKnowsTomorrow** [comment]
24号，天津教育网，不用hosts，G打不开了，Y能打开，看不了视频

**Comment by NeverKnowsTomorrow** [comment]
> 24号，天津教育网，不用hosts，G打不开了，Y能打开，看不了视频

现在，G可以打开，Y打不开了

**Comment by Feiyu-Zhang** [comment]
24号，G Y可以，25号，全挂

**Comment by xuanhui0129** [comment]
25号，天津教育网，全挂

**Comment by machenchen1989** [comment]
> 
> 
> 西安 已挂 o(╯□╰)o youtube能打开但是无法播放视频

西安 一样的

**Comment by suance** [comment]
实测北京教育网所有静态ip地址无法ping通，是否ipv6的墙已经建立起来了？

**Comment by loveklmn** [comment]
> 实测北京教育网所有静态ip地址无法ping通，是否ipv6的墙已经建立起来了？

Use `ping6 web.com` or `ping -6 web.com`

**Comment by LGA1150** [comment]
Duplicate of #276
