### ISSUE TITLE
建议hosts文件改为unix换行符

### ISSUE THREAD

**Issue by ziyuedi** [lennylxx/ipv6-hosts#284]
如题，unix换行符兼容性更好，而且unix-like系统使用者更多

**Comment by lennylxx** [comment]
在桌面OS中，Unix系统用户并不多 https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers
据我所知换行符并不会影响Linux用户hosts文件的解析，如果你真的有需要，可以试试`dos2unix`。
