### ISSUE TITLE
2019年2月18日 教育网部分恢复Youtube视频播放

### ISSUE THREAD

**Issue by RayinTHU** [lennylxx/ipv6-hosts#286]
2019年2月18日中午12:40无意测试发现，北京教育网可以打开Youtube中的一部分视频，并非所有视频均可播放。
搜索的网址依然需要将原来的*.hk转换为*.tw才可用。

**Comment by Guojingxing** [comment]
武汉的教育网已经无法打开所有的YouTube视频了，似乎里面的googlevideo的IPv6地址全部都失效了。该怎么解决？

**Comment by LGA1150** [comment]
@Guojingxing 
见 #282 #285
本 hosts 可能不再更新

**Comment by royccg** [comment]
搜索网址转换为*.tw是什么意思？ 怎么实现啊，同北京教育网

**Comment by ablebodied** [comment]
今天才发现原来教育网也用不了ipv6 hosts了，试了几个网站都不行

**Comment by RayinTHU** [comment]
> 搜索网址转换为*.tw是什么意思？ 怎么实现啊，同北京教育网

就是敲网址的时候，以前是https://www.google.com.hk；
现在变成：https://www.google.com.tw。
