### ISSUE TITLE
大家有没有找到新的路子呢

### ISSUE THREAD

**Issue by hangqm** [lennylxx/ipv6-hosts#287]
ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗

**Comment by wtx626** [comment]
目前访问不了谷歌搜索 学术

**Comment by wtx626** [comment]
谷歌搜索可用了，学术用以下hosts
## Scholar 学术搜索
2404:6800:4004:81a::2003 scholar.google.com
2404:6800:4004:81a::2003 scholar.google.com.hk
2404:6800:4004:81a::2003 scholar.google.com.tw
2404:6800:4004:81a::2003 scholar.google.cn

**Comment by hangqm** [comment]
> 谷歌搜索可用了，学术用以下hosts
> 
> ## Scholar 学术搜索
> 2404:6800:4004:81a::2003 scholar.google.com
> 2404:6800:4004:81a::2003 scholar.google.com.hk
> 2404:6800:4004:81a::2003 scholar.google.com.tw
> 2404:6800:4004:81a::2003 scholar.google.cn

嗯，谷歌学术可用了，给力

**Comment by huangwenweia** [comment]
> ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗

xx-net

**Comment by hangqm** [comment]
> > ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗
> 
> xx-net

xx-net也挺好用的，但是不注册账号会不会只是试用，但是注册账号又要绑定信用卡，感觉很尴尬。

**Comment by mooncn** [comment]
我还是老老实实爬墙吧

**Comment by AzureStar5** [comment]
> > > ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗
> > 
> > 
> > xx-net
> 
> xx-net也挺好用的，但是不注册账号会不会只是试用，但是注册账号又要绑定信用卡，感觉很尴尬。

同问，试用好像用的是公共的appid，貌似所有被墙网站都可以上，Y也可是看视频。但是好像最好要部署自己的appid，可是要绑信用卡。有没有大佬指导一下应该怎么弄

**Comment by huangwenweia** [comment]
> > > ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗
> > 
> > 
> > xx-net
> 
> xx-net也挺好用的，但是不注册账号会不会只是试用，但是注册账号又要绑定信用卡，感觉很尴尬。

不是啊，xx-net分两种，一种收费，一种免费，免费的话貌似是本地账号来的，虽然写着流量，但是你用完之后再重新注册一个账号就行了

**Comment by emrysxw** [comment]
Why educational network  also cannot over the wall through ss？

**Comment by emrysxw** [comment]
Why educational network also cannot over the wall through ss，while it still available for 4G by using ss？

**Comment by hangqm** [comment]
> > > > ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗
> > > 
> > > 
> > > xx-net
> > 
> > 
> > xx-net也挺好用的，但是不注册账号会不会只是试用，但是注册账号又要绑定信用卡，感觉很尴尬。
> 
> 不是啊，xx-net分两种，一种收费，一种免费，免费的话貌似是本地账号来的，虽然写着流量，但是你用完之后再重新注册一个账号就行了

你说的免费和收费都是需要注册账号的吗，xx-net不注册账号倒是也可以用，但是不知道用到什么程度就会有限制。

**Comment by hangqm** [comment]
> > > > ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗
> > > 
> > > 
> > > xx-net
> > 
> > 
> > xx-net也挺好用的，但是不注册账号会不会只是试用，但是注册账号又要绑定信用卡，感觉很尴尬。
> 
> 同问，试用好像用的是公共的appid，貌似所有被墙网站都可以上，Y也可是看视频。但是好像最好要部署自己的appid，可是要绑信用卡。有没有大佬指导一下应该怎么弄

主要就是不太想绑定信用卡，不知道试用是多少流量会限制。

**Comment by huangwenweia** [comment]
> > > > > ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗
> > > > 
> > > > 
> > > > xx-net
> > > 
> > > 
> > > xx-net也挺好用的，但是不注册账号会不会只是试用，但是注册账号又要绑定信用卡，感觉很尴尬。
> > 
> > 
> > 不是啊，xx-net分两种，一种收费，一种免费，免费的话貌似是本地账号来的，虽然写着流量，但是你用完之后再重新注册一个账号就行了
> 
> 你说的免费和收费都是需要注册账号的吗，xx-net不注册账号倒是也可以用，但是不知道用到什么程度就会有限制。

一个账号500M流量，然后账号是本地账号，想创多少就创多少

**Comment by hangqm** [comment]
> Why educational network also cannot over the wall through ss，while it still available for 4G by using ss？

But ss is not free.

**Comment by happyalfred2016** [comment]
> Why educational network also cannot over the wall through ss，while it still available for 4G by using ss？

I think there are more than one pathway of GFW, and there aren't work simultaneously.

**Comment by huangwenweia** [comment]
The GFW is stronger than before

**Comment by ablebodied** [comment]
> > > > > ipv6 hosts这条路子如果真的断了，大家有找到新的路子吗
> > > > 
> > > > 
> > > > xx-net
> > > 
> > > 
> > > xx-net也挺好用的，但是不注册账号会不会只是试用，但是注册账号又要绑定信用卡，感觉很尴尬。
> > 
> > 
> > 同问，试用好像用的是公共的appid，貌似所有被墙网站都可以上，Y也可是看视频。但是好像最好要部署自己的appid，可是要绑信用卡。有没有大佬指导一下应该怎么弄
> 
> 主要就是不太想绑定信用卡，不知道试用是多少流量会限制。

不需要信用卡啊，申请Google app engine 不需要，Google compute engine 才要

**Comment by vincerey** [comment]
我现在连google搜索都进不去了

**Comment by AnyWAT** [comment]
> 不需要信用卡啊，申请Google app engine 不需要，Google compute engine 才要

https://github.com/XX-net/XX-Net/issues/12304#issuecomment-469005590

**Comment by IMconnor** [comment]
要避免DNS污染，并通过ipv6访问谷歌等网站，时下最容易的应该是Firefox吧，直接在连接设置里启用基于HTTPs的DNS就行。不需要改hosts，当然谷歌学术不支持ipv6。YouTube视频当下不能播的问题，等两会完应该就好啦；
如果想在PC上代理DNS查询，dnscrypt-proxy或者unbound（能设置只查询gfwlist中的域名）实现起来也很简单，推荐用dns-over-https/tls，提供商就opendns、谷歌、cloudflare或quad9，这几家都同时支持ipv4和ipv6。openwrt路由器同理，推荐用stubby+dnsmasq，配置简单。
其实自购vps是最省事的，xx-net这是多年前的gae-proxy的马甲吧，应该也好用，但是我记得单日限流？

**Comment by AnyWAT** [comment]
> 单日限流

每个AppID每天1GB

**Comment by wangdsh** [comment]
> 谷歌搜索可用了，学术用以下hosts
> 
> ## Scholar 学术搜索
> 2404:6800:4004:81a::2003 scholar.google.com
> 2404:6800:4004:81a::2003 scholar.google.com.hk
> 2404:6800:4004:81a::2003 scholar.google.com.tw
> 2404:6800:4004:81a::2003 scholar.google.cn

我们的系统检测到您的计算机网络中存在异常流量。使用ipv6 hosts还是上不去😄

**Comment by NeverKnowsTomorrow** [comment]
下一代互联网国家工程中心发布的IPv6 DNS 240c::6666，教育网下可以打开Google，YouTube也能打开，但大部分情况下会一直缓冲，看不了视频

**Comment by ICHx** [comment]
> 下一代互联网国家工程中心发布的IPv6 DNS 240c::6666，教育网下可以打开Google，YouTube也能打开，但大部分情况下会一直缓冲，看不了视频

這個我試過，對部分網站（特別是fb),有污染

**Comment by Alberthoya** [comment]
> 谷歌搜索可用了，学术用以下hosts
> 
> ## Scholar 学术搜索
> 2404:6800:4004:81a::2003 scholar.google.com
> 2404:6800:4004:81a::2003 scholar.google.com.hk
> 2404:6800:4004:81a::2003 scholar.google.com.tw
> 2404:6800:4004:81a::2003 scholar.google.cn

用这个可以打开谷歌学术了，但是目前还是打不开谷歌

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net
Teredo 隧道：https://github.com/XX-net/XX-Net/issues/12455 或原生：https://github.com/XX-net/XX-Net/issues/12477
