### ISSUE TITLE
youtube不能播放，但能使用IDM下载视频

### ISSUE THREAD

**Issue by zzgpku** [lennylxx/ipv6-hosts#288]
使用ipv6 能打开YouTube页面，但不能播放视频，但能通过IDM下载，不知道怎么样将之转化为可使用hosts。
![image](https://user-images.githubusercontent.com/14359560/53237687-3c0c9380-36d2-11e9-9f21-2b062de0d7ec.png)
![image](https://user-images.githubusercontent.com/14359560/53237701-462e9200-36d2-11e9-9cad-62e9a45b0333.png)
![image](https://user-images.githubusercontent.com/14359560/53237720-5a728f00-36d2-11e9-9311-ec1d26b08e09.png)
可以看到，下载过程中IDM将视频来源地址中r3更换为了r1

**Comment by Xiaokeai18** [comment]
我这儿的教育网现在只能google了，youtube页面都打不开

**Comment by Jevengithub** [comment]
今天发现YOUTUBE可以打开并正常播放了，惊喜啊！！！

**Comment by Sean16SYSU** [comment]
> 我这儿的教育网现在只能google了，youtube页面都打不开

这个简单改改hosts就好了。

**Comment by Sean16SYSU** [comment]
但是视频还是看不了

**Comment by XiaoliChan** [comment]
> 但是视频还是看不了

因为googlevideo的地址被墙了
