### ISSUE TITLE
想问一下 Google Play 应用商店的情况

### ISSUE THREAD

**Issue by BDZNH** [lennylxx/ipv6-hosts#293]
最近貌似教育网放松了一些，Google 自己的 v6 IP 可以访问了，但是手机上的play商店可以正常浏览点下载之后一直停在正在下载，完全没有进度。
我想问一下负责下载的域名是哪一段，是不是仍然不可访问。

**Comment by DannyVim** [comment]
请看Wiki页面

**Comment by BDZNH** [comment]
@DannyVim 多谢
