### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ThePigPeppa** [lennylxx/ipv6-hosts#294]
can someone update this, just took a look at this and seems quite outdated

**Comment by LGA1150** [comment]
Are you using CERNET2?

**Comment by ZJUYK** [comment]
maybe you can try xx-net

**Comment by LiveChief** [comment]
@ZJUYK this?
https://github.com/XX-net/XX-Net

**Comment by ZJUYK** [comment]
@LiveChief  yes，the xx-net may satisfy your needs

**Comment by LiveChief** [comment]
@ZJUYK thanks

**Comment by StephenAnboer** [comment]
> Are you using CERNET2?

what's wrong with cernet2?

**Comment by XiaoliChan** [comment]
> > Are you using CERNET2?
> 
> what's wrong with cernet2?

i don't know, before 9 a.m. i can watch video on youtube, but after 9 a.m. i can not watch video on ytb

**Comment by StephenAnboer** [comment]
> > > Are you using CERNET2?
> > 
> > 
> > what's wrong with cernet2?
> 
> i don't know, before 9 a.m. i can watch video on youtube, but after 9 a.m. i can not watch video on ytb

！！！！really?I will try it later

**Comment by dzq8342** [comment]
你们真的不是中国人吗 为什么要用英语

**Comment by XiaoliChan** [comment]
> > > > Are you using CERNET2?
> > > 
> > > 
> > > what's wrong with cernet2?
> > 
> > 
> > i don't know, before 9 a.m. i can watch video on youtube, but after 9 a.m. i can not watch video on ytb
> 
> ！！！！really?I will try it later

really！i had try it again in the morning

**Comment by LiveChief** [comment]
> > > > > Are you using CERNET2?
> > > > 
> > > > 
> > > > what's wrong with cernet2?
> > > 
> > > 
> > > i don't know, before 9 a.m. i can watch video on youtube, but after 9 a.m. i can not watch video on ytb
> > 
> > 
> > ！！！！really?I will try it later
> 
> really！i had try it again in the morning

asked one of the members on JA and they said it worked fine for them.
