### ISSUE TITLE
It seems the education network suddenly can access to Wikipedia(simplified Chinese) without any aid of ladders！

### ISSUE THREAD

**Issue by emrysxw** [lennylxx/ipv6-hosts#298]
Location : Xi'an Jiaotong University
Date: May 27 2019
It is also available for YouTube，all the videos are viewable. 
What is happening?

**Comment by yintianyu** [comment]
坐标Fudan 也都可以了 真神奇

**Comment by IMconnor** [comment]
True. Maybe it's the last test/debug before the 30th anniversary Tiananmen square protest. :)

**Comment by ablebodied** [comment]
I cannot access Wikipedia and YouTube without a ladder, location USTC

**Comment by ICHx** [comment]
starting this week, not using hosts and ladder, can browse utube

**Comment by yintianyu** [comment]
Youtube doesn't work, but zh.wikipedia.org works

**Comment by Guojingxing** [comment]
Not only zh.wikipedia.org works, but also any language! YouTube is also available, but it's hard to say how long it will keep this situation.

**Comment by DannyVim** [comment]
Locate: Shanghai
Status: Working

**Comment by Guojingxing** [comment]
You guys, can you make a livestreaming by OBS studio on YouTube? I tried all the time but no use

**Comment by ablebodied** [comment]
It seems that it cannot work now.  Location:USTC

**Comment by emrysxw** [comment]
Back to the old days！

**Comment by Guojingxing** [comment]
Oh,no. It's been blocked again!

**Comment by Guojingxing** [comment]
YouTube is available now again!

**Comment by ICHx** [comment]
today getting pr-connection-reset for just browsing utube

**Comment by suzhengpeng** [comment]
my vps was blocked and I can not use it to access google and youtube

**Comment by ICHx** [comment]
ps**hon find itself hard to connect since today

**Comment by cyandee** [comment]
大家为啥都要用英语呢

**Comment by dzq8342** [comment]
> 大家为啥都要用英语呢

我早就想问这个问题了

**Comment by cyandee** [comment]
哈哈哈

dzq8342 <notifications@github.com>于2019年7月18日 周四10:11写道：

**Comment by suzhengpeng** [comment]
> 大家为啥都要用英语呢

Maybe ENG is a world language ~

**Comment by dzq8342** [comment]
> > 大家为啥都要用英语呢
> 
> Maybe ENG is a world language ~

用英语讨论自有国情

**Comment by suzhengpeng** [comment]
> > > 大家为啥都要用英语呢
> > 
> > 
> > Maybe ENG is a world language ~
> 
> 用英语讨论自有国情

the Great Qing Dynasty has its own national condition
