### ISSUE TITLE
YouTube视频域名的一些意见

### ISSUE THREAD

**Issue by shuangzhijinghua** [lennylxx/ipv6-hosts#3]
https://docs.google.com/file/d/0B1j-D5SUvWoMNzV4bzFNNUpTT1E/edit?usp=docslist_api
我自己维护的IPv4hosts，YouTube视频方面使用了自己搭的一个SSL代理。
见得比较多的是r?---sn-xxxxxxyy.googlevideo.com的域名，从目前来看x部分和y部分任意组合不一定能通过dns查询到，特定的x只能和特定的y组合，有些x能和很多y组合。而且解析到的域名似乎和访问www.youtube.com时候反馈给www.youtube.com的IP地址有关，用130.211.251.200代理的时候就没解析过61.195.98.156代理的时候出的域名(日本IIJ运营)。
花力气来做重定向的hosts似乎不太有效呢，直接简单暴力收集x部分和y部分，然后批处理去查询组合出来的域名就可以知道什么是存在的什么是不存在的。。目前我自己收集到的情况来看基本涵盖了IPv4亚洲能够访问到的googlevideo.com域名了吧。。
如果需要的话晚点把我收集到的x和y编码发上来。

**Comment by shuangzhijinghua** [comment]
补充谷歌文档的googleusercontent.com没有收录的00-bg，似乎很多hosts都没有收录到bg这一段。刚刚想自己下载一下hosts文件结果发现总打不开，原来解析到doc-00-bg-docs.googleusercontent.com了。

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,速度不错
