### ISSUE TITLE
不要纠结 ipv6了，直接 vpn搞起。shadowsocks 或者v2ray 

### ISSUE THREAD

**Issue by kuaile1993** [lennylxx/ipv6-hosts#300]
不要纠结 ipv6了，直接 vpn搞起。shadowsocks 或者v2ray 。期望国家能明白，翻墙这个事情怎么禁都禁不了的，就算禁了各种vpn  ，也会有人做出新的vpn。除非将中国互联网与世界断开

**Comment by abearxiong** [comment]
shadowsocks要被墙，须得ssr，v2ray

**Comment by DannyVim** [comment]
@abearxiong ssr 不是早就停止开发了吗？

**Comment by abearxiong** [comment]
@DannyVim shadowsocks搭建一次墙一次，ssr好像不会，是停止了
