### ISSUE TITLE
how to use in  windows system

### ISSUE THREAD

**Issue by wangdongming007** [lennylxx/ipv6-hosts#33]
HI ,somebody could tell me how to run this program in windows platform. THX so much!

**Comment by XIAOSpider97** [comment]
Run notepad in ADMIN mode, then open C:\Windows\System32\Drivers\etc\hosts,
then edit it, then save, finally reboot.

CodeMing <notifications@github.com>于2015年10月27日周二 10:59写道：

**Comment by lennylxx** [comment]
This project is for hosts file, which apparently is not a program.
Let me google that for you.
https://en.wikipedia.org/wiki/Hosts_(file)
