### ISSUE TITLE
Some IP blocked

### ISSUE THREAD

**Issue by XIAOSpider97** [lennylxx/ipv6-hosts#34]
Just notice u that 2404:6800:xxxx:200e all IPs ended by 200e r blocked... via connection reset.
At least 809:200e is. I don't know yours since I am currently unable to use IPv6...

**Comment by XIAOSpider97** [comment]
For IP blocking, there r some talks on V2EX.

**Comment by lennylxx** [comment]
I'm aware of this issue, however I'm not sure whether it's the consequence of Google's action or the firewall.
I avoid using them in the hosts file at present.

Here is a list,
```
2404:6800:4005:800::200e 80/443 closed
2404:6800:4005:808::200e unknown
2404:6800:4005:809::200e 80/443 closed
2404:6800:4005:80a::200e 80/443 closed
2404:6800:4005:80b::200e 80/443 closed
```
You can use `nmap` to scan the ports for certain ip.
```
nmap -6 2404:6800:4005:808::200e -p 80,443
```

**Comment by LGA1150** [comment]
All done.
