### ISSUE TITLE
可以告诉我怎么使用这个脚本更新hosts吗

### ISSUE THREAD

**Issue by wangdongming007** [lennylxx/ipv6-hosts#36]
我在CMD 窗口 中的本地文件路径输入  python update_hosts.py
就出现以下的错误提示。

 line 133
   print "There are %d threads working..." % wn
                                         ^
yntaxError: Missing parentheses in call to 'print'

有谁可以给一个可以用的命令行参考一下吗。谢谢！

**Comment by lennylxx** [comment]
Why don't you just search that yourself? Have you already read [this](https://github.com/lennylxx/ipv6-hosts/issues/13)?
Let me Google that for you.
https://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python
It says that maybe you use a Python 3 interpreter.
You can modify the code with parentheses or just use Python 2.
