### ISSUE TITLE
google.cn 443 closed

### ISSUE THREAD

**Issue by LGA1150** [lennylxx/ipv6-hosts#38]
google.cn 系列通过DNS直接解析到的 IPv6 地址（以 a0 结尾）没有开放443，导致不能通过HTTPS访问
经测试，可以使用任意一个443开放的 gws IP，如 `2404:6800:4005:80a::2003`

**Comment by lennylxx** [comment]
Duplicated with https://github.com/lennylxx/ipv6-hosts/issues/34.
The list of blocked IP addresses will be updated in that issue in the future.

**Comment by LGA1150** [comment]
可允许我自行更新？

**Comment by lennylxx** [comment]
@LGA1150  Definitely. You are one of the maintainer now. You have the right to do anything that makes this project better. Just be aware that to use clearer commit message to present the changes.
