### ISSUE TITLE
大部分流量又变成从洛杉矶出了

### ISSUE THREAD

**Issue by LGA1150** [lennylxx/ipv6-hosts#39]
Facebook, Akamai, CloudFlare等大部分IPv6地址都受到影响。Google暂时正常。
希望这只是暂时的

**Comment by mckeyu** [comment]
用那个更新脚本，好多IP都被注释掉了，怎么回事

**Comment by LGA1150** [comment]
@mckeyu 
有些域名（如 `console.developers.google.com` ）并不能查询到AAAA(IPv6)记录，但可以找到它的IPv6地址

**Comment by mckeyu** [comment]
@LGA1150 怎么找的，能告诉我方法吗？

**Comment by LGA1150** [comment]
@mckeyu 
有关谷歌的，见 https://github.com/lennylxx/ipv6-hosts/wiki/Do-It-Yourself
其他暂时不能透露

**Comment by LGA1150** [comment]
已恢复
