### ISSUE TITLE
Android同步服务地址的可能更新

### ISSUE THREAD

**Issue by HankAviator** [lennylxx/ipv6-hosts#4]
Android的该用于同步的地址可能已失效：
>2607:f8b0:4007:804::1007 android.clients.google.com

在设置了Google IPv6 DNS后，重定向`android.clients.google.com`到以上地址（2607:f8b0:4007:804::1007**:0**）可帮助系统解析同步到IPv6而非（纯净的）IPv4地址上。今天11点左右-13:37，同步陆续发生类似于在IPv4下的错误，握手停留在SYNC_SENT阶段，目标主机地址为：

> B0F8:726:408:740::710

目标主机信息：
> **name** Sky Broadband
**location**  Margate, Kent, United Kingdom

我采用隧道方式接入IPv6。桌面以类似方式接入，修改DNS后可正常访问Youtube和谷歌服务。因此怀疑是地址配置的问题。由于nslookup无法从Google IPv6 Public DNS上获取地址，并且我在Windows上不太会用py这个脚本，故请求更新

> 2607:f8b0:4007:804::1007 android.clients.google.com
> *及可能需要的* 
2607:f8b0:4007:804::1004 android-market.l.google.com
2607:f8b0:4007:804::1007 android.l.google.com
> `#2404:6800:4008:c00::64 android-china.l.google.com`

附我的nslookup结果：
（类型=A）
> android.clients.google.com
服务器:  google-public-dns-a.google.com
Address:  2001:4860:4860::8888

>非权威应答:
名称:    android-china.l.google.com
Addresses:  74.125.235.206
          74.125.235.196
          74.125.235.200
          74.125.235.193
          74.125.235.199
          74.125.235.195
          74.125.235.197
          74.125.235.198
          74.125.235.192
          74.125.235.194
          74.125.235.201
Aliases:  android.clients.google.com
          android.l.google.com

（类型=AAAA）
>*** 无法找到服务器 type=AAAA 的地址: Non-existent domain

**Comment by lennylxx** [comment]
我不是很明白你的意思。
`android.clients.google.com` 确实在 DNS 上查不到 AAAA 记录，只有 A 记录。
我是利用 [wiki/1e100.net] (https://github.com/lennylxx/ipv6-hosts/wiki/1e100.net) 的原理，自己给这个域名指定了一个 IP。

如果1007 和 1004 这两个 IP 你用不了，你可以从 [snippets/1e100.net](https://github.com/lennylxx/ipv6-hosts/blob/master/snippets/1e100.txt) 这里 lax 开头的 1e100.net 域名所对应的 IPv6 地址中随便找一个。

比如你可以改成这样：
`2607:f8b0:4007:804::101b android.clients.google.com`
或者这样：
`2607:f8b0:4007:801::1000 android.clients.google.com`

**Comment by HankAviator** [comment]
你好，问题莫名其妙解决了，似乎是我的隧道供应商的问题。已关闭问题，谢谢。
