### ISSUE TITLE
update_hosts.py can't run on windows

### ISSUE THREAD

**Issue by CNMan** [lennylxx/ipv6-hosts#40]
can't recognize dig already in the system path

**Comment by lennylxx** [comment]
Your description is not very clear, sorry we wouldn't be able to help you.

**Comment by cnritng** [comment]
I have dig install in %System32%, command dig work fine,but when i use command "update_hosts.py hosts" ,it tells me "It seems you don't have 'dig' command installed properly on your system."

**Comment by JYzor** [comment]
I have command dig work fine , "It seems you don't have 'dig' command installed properly on your system."  windows 10 .
