### ISSUE TITLE
请问现在还更新吗

### ISSUE THREAD

**Issue by hhhaiai** [lennylxx/ipv6-hosts#45]

**Comment by phy25** [comment]
Latest commit 73e538c 19 days ago

**Comment by hhhaiai** [comment]
能工作吗

**Comment by phy25** [comment]
#30 
And here is for issues only.

**Comment by hhhaiai** [comment]
不好意思。 这样可以直接沟通。

2016-03-02 14:23 GMT+08:00 Phy <notifications@github.com>:

**Comment by hhhaiai** [comment]
我这里是不可以工作的。我这里hosts IPV4部分可用，IPV6的 支持一些功能，比ipv4好些。
所以想更新个 IPV4 ipv6通用版本。跟您这边沟通下


2016-03-02 14:36 GMT+08:00 sanbo x <sanbo.xyz@gmail.com>:

**Comment by LGA1150** [comment]
遇到了什么问题？

**Comment by hhhaiai** [comment]
能分享下hosts更新的策略吗。这样更多人可以参与更新校正策略

2016-03-02 15:14 GMT+08:00 LGA1150 <notifications@github.com>:

**Comment by lennylxx** [comment]
1. 项目名称为 ipv6-hosts，因此是 IPv6 only。
2. 遇到了问题，请描述清楚自己遭遇的状况和尽可能详细的说明，并附上自己尝试的过程。
3. 开 issue 之前请先看 https://github.com/lennylxx/ipv6-hosts/issues/13 ，并搜索其他已经关闭的 issue，不要只写一个标题。
4. 关于更新 hosts 的策略，请详细并完整看过本项目的代码和 wiki 之后再来提问。
