### ISSUE TITLE
hosts中是不是有些域名已经失效

### ISSUE THREAD

**Issue by nolitus** [lennylxx/ipv6-hosts#47]
比如苹果Apple的

**Comment by LGA1150** [comment]
请给出具体域名

**Comment by nolitus** [comment]
## Apple 苹果
2600:1415:5:185::c77 www.apple.com #www.isg-apple.com.akadns.net

**Comment by nolitus** [comment]
## Apple 苹果
2600:1415:5:185::c77 www.apple.com #www.isg-apple.com.akadns.net

**Comment by nolitus** [comment]
intel的域名也不行
