### ISSUE TITLE
Youtube和Intel的问题

### ISSUE THREAD

**Issue by nolitus** [lennylxx/ipv6-hosts#48]
Intel的这个已经失效了貌似：2600:1417:9::6007:3629
YouTube视频已经经常加载不出来了，不知道是不是有的域名已经失效了......

**Comment by LGA1150** [comment]
YouTube新增了一组服务器，暂时未能添加

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,速度不错
