### ISSUE TITLE
发现些神奇的googlevideo.com，并不能用conv.py进行互相转换

### ISSUE THREAD

**Issue by fengixng** [lennylxx/ipv6-hosts#49]
r1---sn-bvvbax-v8cl.googlevideo.com
r1---sn-ug5onuxaxjvh-n8v6.googlevideo.com
r1---sn-juh-h4hz.googlevideo.com
这些sn编码有的虽然是八位，但是有-这个符号，有些不是八位的，脚本只能转换8位的，并且不能识别-这个符号

**Comment by XIAOSpider97** [comment]
这种一般都是GGC。

fengixng <notifications@github.com>于2016年3月25日周五 03:11写道：

**Comment by LGA1150** [comment]
用 -g 参数
`python conv.py -g bvvbax-v8cl`
