### ISSUE TITLE
accounts.gstatic.com等几个域名请添加

### ISSUE THREAD

**Issue by shuangzhijinghua** [lennylxx/ipv6-hosts#5]
新版谷歌服务已经不使用accounts.google.com转而使用accounts.gstatic.com
请添加chrome数据压缩的域名:
proxy.googlezip.net
compress.googlezip.net
check.googlezip.net
proxy-dev.googlezip.net
另外twitter启用了新的IP:185.45.4.0/22 .其实原生推特和FB地址已经越来越少,有一天就用一天吧.199.16.156.0/22现在只剩下几个无关紧要的IP了...

**Comment by shuangzhijinghua** [comment]
cloud.google.com
console.developers.google.com
两个Google Cloud域名请添加.

**Comment by popcorner** [comment]
楼上注意：cloud.google.com是可以解析的
console.developer.google.com没有ipv6地址
