### ISSUE TITLE
好像YouTube又失效了？

### ISSUE THREAD

**Issue by nolitus** [lennylxx/ipv6-hosts#51]
2404:6800:4005:808::2003  完全打不开

**Comment by crytography** [comment]
我也打不开

**Comment by LGA1150** [comment]
Google最近频繁调整服务器

**Comment by hahahahahuo** [comment]
是啊是啊，打不开。最近调整之后下载很慢。

2016-04-12 18:16 GMT+08:00 LGA1150 <notifications@github.com>:

**Comment by hahahahahuo** [comment]
在这次紧急调整的hosts释放出来30分钟之后看到了，突然想，如果不用hosts扶正呢？发现服务/产品页面只有Play、Video搜索、Apps被“连接已重置”，AdSense一如既往地CSS加载失败，YouTube视频下载速度还快了一些。学院路，有被跳转到co.jp的倾向。这个网络搞不清啊！

**Comment by hahahahahuo** [comment]
Google Play也能自然打开了，不过Gmai中Gmail被调整为禁用了，这动作也是没谁了、
![default](https://cloud.githubusercontent.com/assets/12572008/14458818/7a14bc40-00e6-11e6-9c64-1fc04c5a25c4.JPG)

**Comment by BruceZac** [comment]
problem solved thanks to @LGA1150 , very appreciated. please make this issue closed, @nolitus

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,还可以看很多海外禁网新闻，速度不错
