### ISSUE TITLE
could someone tell me how to use the script

### ISSUE THREAD

**Issue by wangdongming007** [lennylxx/ipv6-hosts#52]
I use python 3 ,and i have been translate Python 2 to 3 code .

so here is my question:

if i want to update the hosts file, what command line should i type ?

i try to use this :

`E:\ipv6-hosts-master>python update_hosts.py -t  E:\ipv6-hosts-master\hosts`

and have  reminder as:

`You must specify the input hosts file (only one).`

could someone tell me how to utilize the script . Thx very much!

**Comment by CNMan** [comment]
see https://github.com/lennylxx/ipv6-hosts/blob/master/update_hosts.py#L211 to L222
