### ISSUE TITLE
Hey, how about adding the NYTimes IPv4 domain?

### ISSUE THREAD

**Issue by BruceZac** [lennylxx/ipv6-hosts#53]
I like reading NYTimes very much, as  resource of news, they are probably the most professional and humanitarian news agency I ever seen, of course you can say I'm very short-sighted, they have won many [Pulitzer Prizes ](https://www.google.com.hk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#newwindow=1&q=the+new+york+times+awards&stick=H4sIAAAAAAAAAONgFuLQz9U3MM82SlGCs7Rks5Ot9BPLE4tSIGR8eWZeXmqRFZhT_IgxhFvg5Y97wlLek9acvMboyoVfvZAKF5trXklmSaWQFBePFNwaDQYpLi44jwcAEFz6M4wAAAA) .
it's IPv4 provided only and been blocked forever, so please and thx very much.
(BTW, written in En instead of Ch is not kind of ZhuangBi, just for assurance that this message not searched by Ch search engine)

**Comment by XIAOSpider97** [comment]
This makes no sense.
AFAIK the blocking methods of nytimes is not only DNS poisoning.
Their IPs were null routed.
Domain will cause HTTP connection reset and they don't support SSL.

BruceZac <notifications@github.com>于2016年4月18日周一 10:19写道：

**Comment by LGA1150** [comment]
然并卵，域名不支持https，即使忽略证书错误强制访问也会http 502

**Comment by hahahahahuo** [comment]
https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac

2016-04-18 12:47 GMT+08:00 LGA1150 <notifications@github.com>:

**Comment by hahahahahuo** [comment]
用这个扩展，纯IPv6下能打开www.nytimes.com

2016-04-18 13:04 GMT+08:00 宿强 <hahahahahuo@gmail.com>:

**Comment by BruceZac** [comment]
I see, thanks!

**Comment by BruceZac** [comment]
谢谢回复，网络菜鸟提了一个很low的问题，感谢不骂之恩，并感谢 @hahahahahuo提供的方法

**Comment by LGA1150** [comment]
NYT 貌似已支持 https，可以加入了
