### ISSUE TITLE
YOUTUBE的某段域名失效了

### ISSUE THREAD

**Issue by shetz163** [lennylxx/ipv6-hosts#55]
2a00:1450:4009::这个段全面失效了
ping了一下对应的网址  给的是2a00:1450:401f:这个段

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,还可以看很多海外禁网新闻，速度不错
