### ISSUE TITLE
iata和sn互相转换出现错误

### ISSUE THREAD

**Issue by fengixng** [lennylxx/ipv6-hosts#56]
我发现`cbf02s**` 里面的转换都出现错误

例如：cbf02s04正确的转换应该是jc47lu7z，但是错误的转换为jc47ln7z

反之jc47lu7z和jc47ln7z都能转换为cbf02s04

**Comment by fengixng** [comment]
`par03s06`也出现了错误，正确的为`25g7sm7d`，但是错误的转换为`25g7sn7d`

**Comment by fengixng** [comment]
还有`a5m7zn7e`，这是错误的，`a5m7zu7e`这个才是正确的

**Comment by lennylxx** [comment]
https://github.com/lennylxx/ipv6-hosts/wiki/sn-domains
这篇文章的第3条里面提到了转换规则。

iata -> sn 默认是用的 n，之所以这么做是因为s可以对应到n和u，从s转换的时候两个你应该选哪个呢？
这需要另外提供IPv6地址才能解决这个问题。
而从n和u转为s就简单了，直接全部换成s。
就是一个对应关系，一个方向是二对一，一个方向是一对二，代码为了简洁没有实现这部分功能。

另外m大多数情况只会出现在IPv4地址中，而IPv4不是本项目关注的重点，所以转换工具也就没考虑这个问题，默认都是IPv6。

**Comment by fengixng** [comment]
抱歉，我没有仔细看wiki，所以才提出这样的问题
我认为是否可以在穷举的时候把全部可能给列出来，而不是现在只列出可能性最大的n。
我不知道这样做在代码上实现的难度怎么样，如果说错了请见谅

**Comment by lennylxx** [comment]
代码可以不用穷举，可以直接传入IPv6的地址作为一个参数，然后判断范围就可以了。
但是这样做转换工具需要额外的参数，就不仅仅是现在这样只传入`cbf02s0`这个字符串就可以的。

**Comment by fengixng** [comment]
我指的是使用list-sn.py穷举的时候是否可以吧S,M,U的结果全部给穷举出来

**Comment by fengixng** [comment]
@lennylxx 有些GGC是五位而不是四位，无法使用conv.py进行转换，会提示错误，例如：`5np5po4v-c33ek`
