### ISSUE TITLE
2607:f8b0:4007:804::100e dl.google.com 使 ubuntu 14  无法正常更新chrome

### ISSUE THREAD

**Issue by Overvenus** [lennylxx/ipv6-hosts#6]
2607:f8b0:4007:804::100e dl.google.com #dl.l.google.com

这条使 ubuntu 无法更新 chrome.

```bash
apt-get upgrade
  ...
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg  Connection failed
  ...
```

注释掉这条记录后可以正常更新 chrome.
```bash
apt-get update
  ...
Get:1 http://dl.google.com stable Release.gpg [198 B]
  ...
```

我的环境:  ubuntu14, 浙江地区 ipv6.

最后，感谢作者提供该项目.

**Comment by lennylxx** [comment]
我在自己电脑上测试是可以下载的。
你把地址换成 `2607:f8b0:4007:805::1009` 试试。

**Comment by Overvenus** [comment]
这个 ```2607:f8b0:4007:805::1009``` 也不行， 不过我用 ```203.208.48.128``` 更新好了。

**Comment by Overvenus** [comment]
这个 ```2404:6800:4005:800::1007 dl.google.com```  在我这可以正常更新.
