### ISSUE TITLE
compablity under the windows system with python 3.4

### ISSUE THREAD

**Issue by DarwinniwraD** [lennylxx/ipv6-hosts#61]
there are some problems about the update.py file under the windows system with the python 3.4, such as the print function, it need to be wrapped into brackets, and the data type wrong, and so on. so any one could update it for the windows? thank you 
 and here is my quesion, could some one know what's wrong with it? thank you!
`Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "update.py", line 102, in run
    cname, ip = query_domain(domain, False)
  File "update.py", line 171, in query_domain
    if cname == '' and validate_domain(v[:-1]):
  File "update.py", line 182, in validate_domain
    m = p.match(domain)
TypeError: can't use a string pattern on a bytes-like object`

**Comment by lennylxx** [comment]
Please use python 2.7, thanks.
