### ISSUE TITLE
新更新的hosts无法使用github

### ISSUE THREAD

**Issue by sonyangchang** [lennylxx/ipv6-hosts#62]
最新跟新的host文件，发现使用浏览器无法显示github的页面，删掉与github相关的IP，发现好使。

**Comment by LGA1150** [comment]
具体是什么错误？
注意，既然是 IPv6-hosts , 就必须在有IPv6的环境下才能使用

**Comment by BruceZac** [comment]
我也发现了这个问题，注释掉有关Github的行就可以上了，是IPv6环境

**Comment by hahahahahuo** [comment]
昨天还没有出现这样的问题，今天也中招儿了。Github真心不简单，好多地址都不是直接访问就可以的。

2016-07-14 23:18 GMT+08:00 BruceZac <notifications@github.com>:
