### ISSUE TITLE
IPV6 Host not performing well on Youtube

### ISSUE THREAD

**Issue by Ficklee** [lennylxx/ipv6-hosts#65]
亲测IPv6的IP访问Youtube视频时出现加载缓慢甚至失败情形。部分只能加载成功较低画质影片。

The hosts was slow and even failed to load videos on Youtube. For the other videos, only low-definition movies can be loaded when using IPv6 hosts to connect Youtube.

**Comment by Phecda** [comment]
我遇到过两次，后来发现是谷歌新增了域名。如果你用 Chrome 的话，查看一下控制台，是否有一个形如 `r1---sn-gxuxapu-hm2e.googlevideo.com` 的域名 GET 失败（可能需要较长时间才会显示失败）。如果是的话，按照 [这篇 Wiki](https://github.com/lennylxx/ipv6-hosts/wiki/Do-It-Yourself) 的第二部分自行添加。希望可以帮到你。

**Comment by LGA1150** [comment]
如果你找到了新域名，可以提交 Pull Request

**Comment by Ficklee** [comment]
谢谢 @Phecda 和 @LGA1150 两位。问题确实得到了解决。在北京地区Google增加了至少4个sn域名。我添加了两次后确认连接恢复。

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,还可以看很多海外禁网新闻，速度不错
