### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by maxchendt** [lennylxx/ipv6-hosts#66]
GFW 又涨高了

https://twitter.com 被reset
https://support.twitter.com/  却好好的

无论是使用 hosts文件，还是自己起的dns服务器

自己起的dns服务器，解析结果如下
> support.twitter.com
Name:    support.twitter.com
Addresses:  104.244.42.199, 104.244.42.7, 104.244.42.71, 104.244.42.135

> twitter.com
Name:    twitter.com
Addresses:  104.244.42.193, 104.244.42.65

**Comment by posclegom** [comment]
可能是传说中的SNI攻击。

可以试一下在XP上使用IE8看能不能同时打开两个网址（当然还是要继续使用HOSTS方法）。

**Comment by LGA1150** [comment]
主站 twitter.com 的所有IP被墙，暂未发现新IP
