### ISSUE TITLE
android 5.1使用了新的连接检测域名，请添加

### ISSUE THREAD

**Issue by shuangzhijinghua** [lennylxx/ipv6-hosts#7]
connectivitycheck.android.com
顺便twitter的地址更新一下吧。。

**Comment by lennylxx** [comment]
Twitter IP 太难找了，实在不想更新 XD。
不如你发起一个 Pull Request :smile:

**Comment by lennylxx** [comment]
`185.45.5.34` 这个速度不错
但是 `*.twimg.com` 的 IP 还没找到合适的

**Comment by shuangzhijinghua** [comment]
呃。。我只是个鶸，还不太会玩github.
117.18.237.139用twimg应该可以，不过twitter主站显示的图片也是从twitter.com拉下来的，所以主站速度决定图片载入速度。
199.16.158.72 twitter.com
185.45.5.34 www.twitter.com
我是这样用的。

**Comment by shuangzhijinghua** [comment]
话说googlevideo之类分配服务器的时候是根据https://redirector.googlevideo.com/report_mapping 显示的IP来分配最近的服务器，hosts里面是不是也根据了这个来写的？

**Comment by lennylxx** [comment]
我用的是学校的 isatap 服务器，返回的内容是这样的。
`2001:da8:203:666:200:5efe:xxxx:xxxx => ronix-otp1 (2001:da8:203::/48)`

至于 hosts 文件我只是把 `redirector.goooglevideo.com` 重定向到了 洛杉矶。

**Comment by LGA1150** [comment]
*.twimg.com 可以用199.96.57.2、192.229.237.25。
117.18.237.139似乎不太稳定
