### ISSUE TITLE
能否自行添加 GGC 地址？

### ISSUE THREAD

**Issue by Phecda** [lennylxx/ipv6-hosts#70]
发现 YouTube 会从一些新的 GGC 传输数据，由于hosts 里没有这些新地址，一些视频无法播放。请问是否有办法像自行添加 SN Domains 一样添加 GGC ？

另外，为什么在一台电脑上访问 YouTube ，不同时候同一个视频会分配不同的视频来源？比如以前我一直在用 SN Domain ，现在不得不用 GGC？

**Comment by lennylxx** [comment]
当然可以，但是前提是你要先知道这些地址，然后找到对应的IPv6就可以了。
一个比较笨但是有效的做法是打开浏览器的developer tool，查看无法访问的视频地址是哪一类的。

**Comment by Phecda** [comment]
地址已经找到了，然而不知道怎么获得对应的 IPv6 地址。

**Comment by lennylxx** [comment]
把这些地址按行组织成一个文本文件，然后运行`./update_hosts.py -i new_hosts.txt`

**Comment by Phecda** [comment]
没有 `-i` 这个参数，不过用了 `./update_hosts.py new_url.txt -o new_hosts.txt` 起到了同样的作用。
