### ISSUE TITLE
如果 update_hosts 无法找到地址怎么办？

### ISSUE THREAD

**Issue by Phecda** [lennylxx/ipv6-hosts#79]
如图：
![image](https://cloud.githubusercontent.com/assets/8066567/18833301/91ae0432-8422-11e6-8d5c-00807ea3e330.png)

对于 `a5mekney` 这部分的 sn 域名，`update_hosts.py` 会把它注释掉
![qq 20160926195404](https://cloud.githubusercontent.com/assets/8066567/18833407/0de87ba4-8423-11e6-9867-1b88a872f33f.png)

这样一来就无法获取到其 IP 地址。请问有什么解决办法吗？

**Comment by lennylxx** [comment]
那只能根据地址分配规律猜测了，一般查不到时因为IPv6还未启用。不过不排除已经启用但是DNS中没有缓存，虽然这种情况几乎不可能。
按照已知的地址往后顺延，然后测试能否连的上。
