### ISSUE TITLE
YouTube 近期加载视频缓慢

### ISSUE THREAD

**Issue by lennylxx** [lennylxx/ipv6-hosts#8]
近期我这里有很大几率会从下面的服务器请求视频，延时很高。
```
2001:7f8:49:1::c r1---sn-gvopm-vu2e.googlevideo.com
2001:7f8:49:1::d r2---sn-gvopm-vu2e.googlevideo.com
2001:7f8:49:1::e r3---sn-gvopm-vu2e.googlevideo.com
2001:7f8:49:1::f r4---sn-gvopm-vu2e.googlevideo.com
2001:7f8:49:1::10 r5---sn-gvopm-vu2e.googlevideo.com
2001:7f8:49:1::11 r6---sn-gvopm-vu2e.googlevideo.com
```
查询得知位于布鲁塞尔：
http://www.tcpiputils.com/browse/ipv6-address/2001:7f8:49:1::c
其他关键信息：
```
inet6num: 2001:7f8:49::/48
netname: RoNIX-20090127
descr: Asociatia Nationala a Internet Service Providerilor din Romania
descr: Romanian Internet Exchange
country: RO

route6: 2001:7f8:49::/48
descr: RoNIX-IPv6
origin: AS20530
mnt-by: GDR-MNT
source: RIPE # Filtered
```

https://redirector.googlevideo.com/report_mapping 查询结果
`2001:da8:203:666:200:5efe:xxxx:xxxx => ronix-otp1 (2001:da8:203::/48)`

看到两者都有关键词 `ronix`，看来是根据我的 IP 给我分配了 `ronix` 的服务器。
然后搜到了 https://forums.he.net/index.php?topic=3285.0

管理员说可能是 RoNIX 缓存的问题。

为什么 Google 不给我分配美国的服务器？是 Google 的问题，还是HE 或者是 RoNIX 的路由设置有问题？
有没有解决办法？

**Comment by shuangzhijinghua** [comment]
那不就只能更换IP咯，YouTube.com/YouTube-nocookie.com都指一个能get到美国服务器的sniproxy上面。

**Comment by lennylxx** [comment]
对，只能伪装自己的 IP，但是用代理必须要有国外的服务器。
这与我最初的“只用 hosts + HTTPS” 的设想相悖。

或者等 Google 什么时候发善心调整下规则。
这个人听他语气貌似是 Youtube 员工，他承诺会帮助解决这个问题：
https://www.reddit.com/r/youtube/comments/2jvono/getting_slow_youtube_help/

**Comment by shuangzhijinghua** [comment]
直连的时候都遇到过分配到5uaezn服务器的，ping延迟都500多ms

**Comment by lennylxx** [comment]
看前缀应该是亚特兰大，没那么慢啊，我这里220ms左右。

**Comment by shuangzhijinghua** [comment]
IPV4的。V6可能快一些

**Comment by shuangzhijinghua** [comment]
现在解析到的是nx57yn服务器，应该正常了，虽然redirector还显示的是ronix

**Comment by shuangzhijinghua** [comment]
![image](https://cloud.githubusercontent.com/assets/7972337/7468526/4e0e575e-f33c-11e4-8767-91be701d16d9.png)
今天通过香港tunnelbroker开始解析到很多奇奇怪怪的IP，每刷新一次都不一样。

**Comment by shuangzhijinghua** [comment]
r7---sn-cnoa-h55l.googlevideo.com
添加一下吧。

**Comment by lennylxx** [comment]
已添加，不过这些 IP 好像是印度的，国内应该不常访问到。

**Comment by shuangzhijinghua** [comment]
好像wiki没有收录i3b7kn??的。
名称:    r1.sn-i3b7kn7r.googlevideo.com
Addresses:  2404:6800:4005:17::7
          74.125.106.23

**Comment by lennylxx** [comment]
已更新。和本issue无关的内容请新开issue。

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube，速度不错
