### ISSUE TITLE
hosts 文件里的一些格式问题

### ISSUE THREAD

**Issue by wang20150419** [lennylxx/ipv6-hosts#80]
第 200、203、312、410、452、453、572、696、828、909、2550、2577 格式错误，建议注释掉。

**Comment by lennylxx** [comment]
你说的应该是通配符，那些域名是从原项目继承过来的。
然而 hosts 不支持通配符，一般会忽略掉。
有什么特别的原因必须要注释掉吗？

**Comment by CNMan** [comment]
http://unbound.nlnetlabs.nl/svn/trunk/contrib/build-unbound-localzone-from-hosts.pl
`#`之后能否跟一个空格或者删除cname注释？转换unbound格式时有点问题,例如
```
local-data: "#ipv6.google.com AAAA 2404:6800:4005:80b::2003"
```
