### ISSUE TITLE
求助，google ipv6 ip 全部失效

### ISSUE THREAD

**Issue by 88954275** [lennylxx/ipv6-hosts#82]
求助，9月中下旬以后学校内部所有google的ipv6地址无法访问，表现为可以ping出ipv6地址，但是全部请求超时。其他ipv6网站正常访问，不知是学校单独现象还是整体情况，如何破解？谢谢！

**Comment by LGA1150** [comment]
强制https.

**Comment by zviets** [comment]
沈阳没问题。chrome+Https Everywhere。
但是FB的头像和照片基本都挂。

**Comment by nolitus** [comment]
twitter挂了

**Comment by StephenAnboer** [comment]
楼主还有继续更新吗？这一版youtube有些不正常了

**Comment by AlexanderMisel** [comment]
@StephenAnboer 这是我自己用的，里面*.googlevideo.com的都改了，你可以看看。
[hosts.txt](https://github.com/lennylxx/ipv6-hosts/files/815853/hosts.txt)
