### ISSUE TITLE
关于YouTube SN域名

### ISSUE THREAD

**Issue by LGA1150** [lennylxx/ipv6-hosts#9]
我发现，wiki中的两个密码表，其实可以合并为一个：
| 6(5) d(6) k(7) r(8) y(9) |
| 5(a) c(b) j(c) q(d) x(e) |
| 4(f) b(g) i(h) p(i) w(j) |
| 3(k) a(l) h(m) o(n) v(o) |
| 2(p) 9(q) g(r) n(s) u(t) |
| 0(u) 8(v) f(w) m(x) t(y) |
| 1(z) 7(0) e(1) l(2) s(3) | z(4)
括号里为原文
因此原文与编码后的结果属于一种“映射”关系

至于r?---sn-xxxxxxxxxxxx（任意数量）-xxxx（3~5位）.googlevideo.com域名，其实就是GGC服务器经过以上的编码“映射”得到的。xxxxxxxxxxxx（任意数量）为编码后的[ISP名称]，xxxx（3~5位）为编码后的[IATA代码+0~2位数字]。

例子：
编码前：r1---xo-lax5.googlevideo.com
编码后：r1---sn-mv-a5m6.googlevideo.com

**Comment by lennylxx** [comment]
嗯。确实可以合并，当时我之所以分开是为了别人容易看懂，代码里的table就是合并在一起的。

**Comment by LGA1150** [comment]
因此你的转换程序也得更新一下以支持 r?---sn-xxxxxxxxxx-xxxx.googlevideo.com的域名

**Comment by lennylxx** [comment]
已更新。

**Comment by LGA1150** [comment]
@lennylxx 你在[这里面](https://github.com/lennylxx/ipv6-hosts/wiki/GGC)说
> `r?---sn-[isp name]-[loc][x].googlevideo.com`
> `[x]` is the encoded number of server group, length is `1`.

实际上，x 的长度可以为2，比如 `r1---sn-i3co-i3be7.gvt1.com` ，对应 `r1---hkbn-hkg10.gvt1.com`

**Comment by XIAOSpider97** [comment]
这种代码的都是GGC。不过确实可以是2，hinet的也是2

LGA1150 <notifications@github.com>于2015年10月30日周五 10:04写道：

**Comment by lennylxx** [comment]
我做出这样的判断是因为当时搜集到的信息，看来 wiki 需要更新。
