### ISSUE TITLE
coursera 上的视频和图片无法访问

### ISSUE THREAD

**Issue by WuPeng2016** [lennylxx/ipv6-hosts#95]
你好，最近coursera 上的视频和图片无法访问，貌似是cloudfront和amazonaws相关的，可以解决一下吗？

**Comment by lennylxx** [comment]
你好，本项目主要关注IPv6，你说的应该是d3njjcbhbojbot.cloudfront.net，但我并没有查询到IPv6地址，抱歉无法解决。
另外，以后开issue请提供详细的信息并确认是与本项目相关的问题。

**Comment by phy25** [comment]
> For existing web distributions, you can enable IPv6 through the Amazon CloudFront console or API.

https://aws.amazon.com/cn/about-aws/whats-new/2016/10/ipv6-support-for-cloudfront-waf-and-s3-transfer-acceleration/

Coursera 没开，所以不行，无法解决。
