### ISSUE TITLE
最近一到两版HOSTS更新后安卓PLAY商店和YOUTUBE用不了

### ISSUE THREAD

**Issue by kagurainroy** [lennylxx/ipv6-hosts#98]
同样的HOSTS PC上可以任意访问GOOGLE、YOUTUBE
安卓上用CHROME浏览器也能正常访问GOOGLE、PLAY、YOUTUBE 
但是PLAY商店的APP和YOUTUBE APP 却无限转圈

**Comment by kagurainroy** [comment]
尝试刷了RR、LINEAGE、魔趣三个ROM 都失败

**Comment by kagurainroy** [comment]
GOOGLE应用也能正常用 这就很尴尬啊

**Comment by Isaccliberty** [comment]
我怀疑是在登录认证的过程中的某台服务器没有在hosts名单里，或者只支持v4（应该不是）这个问题同样困扰我很久了。

**Comment by boxfox333** [comment]
网站能上，应用不能用，一头雾水

**Comment by lennylxx** [comment]
应该是https://github.com/lennylxx/ipv6-hosts/commit/56ff9074f09a20a329c9130fa71efdd0c85cea3c 把 android.clients.google.com 和 android.l.google.com 给注释掉了，最近的几个Pull Request太大了，没有全部自己看。我自己现在也没有IPv6环境，你们能帮忙测试一下把这两行取消注释可不可行吗？

**Comment by kagurainroy** [comment]
最新一版已经可以正常食用安卓APP

**Comment by lennylxx** [comment]
刚才发现https://github.com/lennylxx/ipv6-hosts/pull/96 好像把hosts更新坏了，IP全变成了法国的，现在访问速度比较慢，我会尽快修复。

**Comment by lennylxx** [comment]
0b1ab0c8d887b0a945e03a745a2beae25625ca14 使用了台北的IP进行加速
